# -*- coding: utf-8 -*-

"""
lispublicservices

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class AccessLevelEnum(object):

    """Implementation of the 'AccessLevel' enum.

    Gets or sets the access level.

    Attributes:
        NONE: TODO: type description here.
        READ: TODO: type description here.
        UPDATE: TODO: type description here.
        INSERT: TODO: type description here.
        DELETE: TODO: type description here.

    """

    ENUM_NONE = 'None'

    READ = 'Read'

    UPDATE = 'Update'

    INSERT = 'Insert'

    DELETE = 'Delete'
