# -*- coding: utf-8 -*-

"""
lispublicservices

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class AppointmentTypeEnum(object):

    """Implementation of the 'AppointmentType' enum.

    Gets or sets the type of the appointment.

    Attributes:
        FIX: TODO: type description here.
        PLAN: TODO: type description here.
        TARGET: TODO: type description here.
        OPTIMAL: TODO: type description here.
        ORIGINAL: TODO: type description here.
        DISPATCHCALCULATED: TODO: type description here.
        DISPATCHMANUAL: TODO: type description here.
        TRAILERETA: TODO: type description here.

    """

    FIX = 'Fix'

    PLAN = 'Plan'

    TARGET = 'Target'

    OPTIMAL = 'Optimal'

    ORIGINAL = 'Original'

    DISPATCHCALCULATED = 'DispatchCalculated'

    DISPATCHMANUAL = 'DispatchManual'

    TRAILERETA = 'TrailerETA'
