# -*- coding: utf-8 -*-

"""
lispublicservices

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class BlockingWeightBaseEnum(object):

    """Implementation of the 'BlockingWeightBase' enum.

    Gets or sets BlockingWeightBase.

    Attributes:
        NONE: TODO: type description here.
        LOADINGMETER: TODO: type description here.
        CUBICDECIMETER: TODO: type description here.
        SQUAREMETER: TODO: type description here.
        STORAGEPLACE: TODO: type description here.

    """

    ENUM_NONE = 'None'

    LOADINGMETER = 'LoadingMeter'

    CUBICDECIMETER = 'CubicDecimeter'

    SQUAREMETER = 'SquareMeter'

    STORAGEPLACE = 'StoragePlace'
