# -*- coding: utf-8 -*-

"""
lispublicservices

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class BorderoKindEnum(object):

    """Implementation of the 'BorderoKind' enum.

    Gets or sets BorderoKind.

    Attributes:
        NONE: TODO: type description here.
        WITHPICKUP: TODO: type description here.

    """

    ENUM_NONE = 'None'

    WITHPICKUP = 'WithPickup'
