# -*- coding: utf-8 -*-

"""
lispublicservices

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class CalculationBaseEnum(object):

    """Implementation of the 'CalculationBase' enum.

    Gets or sets the CalculationBase property. This property depends on the
    database field GueltigF.

    Attributes:
        NOTSET: TODO: type description here.
        DEBIT: TODO: type description here.
        CREDIT: TODO: type description here.
        ALL: TODO: type description here.

    """

    NOTSET = 'NotSet'

    DEBIT = 'Debit'

    CREDIT = 'Credit'

    ALL = 'All'
