# -*- coding: utf-8 -*-

"""
lispublicservices

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class CancellationStateEnum(object):

    """Implementation of the 'CancellationState' enum.

    Gets or sets the CancellationState property. This property depends on the
    database field DelKz.

    Attributes:
        NOTSET: TODO: type description here.
        SHOULDBEDELETED: TODO: type description here.
        DELETED: TODO: type description here.

    """

    NOTSET = 'NotSet'

    SHOULDBEDELETED = 'ShouldBeDeleted'

    DELETED = 'Deleted'
