# -*- coding: utf-8 -*-

"""
lispublicservices

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class CarrierConditionTypeEnum(object):

    """Implementation of the 'CarrierConditionType' enum.

    Gets or sets the type of the carrier condition.

    Attributes:
        NOTSET: TODO: type description here.
        MANUAL: TODO: type description here.
        MASTERDATA: TODO: type description here.
        COMMON: TODO: type description here.

    """

    NOTSET = 'NotSet'

    MANUAL = 'Manual'

    MASTERDATA = 'Masterdata'

    COMMON = 'Common'
