# -*- coding: utf-8 -*-

"""
lispublicservices

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class CreditInvoicingPeriodGroupingEnum(object):

    """Implementation of the 'CreditInvoicingPeriodGrouping' enum.

    Gets or sets CreditInvoicingPeriodGrouping.

    Attributes:
        NOTACTIVE: TODO: type description here.
        LOADINGDATE: TODO: type description here.
        ORDERDATE: TODO: type description here.

    """

    NOTACTIVE = 'NotActive'

    LOADINGDATE = 'LoadingDate'

    ORDERDATE = 'OrderDate'
