# -*- coding: utf-8 -*-

"""
lispublicservices

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class CreditConditionCodeEnum(object):

    """Implementation of the 'CreditConditionCode' enum.

    Gets or sets CreditConditionCode.

    Attributes:
        NOTSET: TODO: type description here.
        MANUEL: TODO: type description here.
        MASTERDATA: TODO: type description here.
        COMMON: TODO: type description here.
        POSITION: TODO: type description here.
        DEBKRE: TODO: type description here.
        DEBKREWAV: TODO: type description here.

    """

    NOTSET = 'NotSet'

    MANUEL = 'Manuel'

    MASTERDATA = 'Masterdata'

    COMMON = 'Common'

    POSITION = 'Position'

    DEBKRE = 'DEBKRE'

    DEBKREWAV = 'DEBKREWAV'
