# -*- coding: utf-8 -*-

"""
lispublicservices

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class CreditBookingEnum(object):

    """Implementation of the 'CreditBooking' enum.

    Gets or sets CreditBooking.

    Attributes:
        NO: TODO: type description here.
        YES: TODO: type description here.
        TODIFFERENTACCOUNTS: TODO: type description here.
        DIVISIONDEPENDENT: TODO: type description here.

    """

    NO = 'No'

    YES = 'Yes'

    TODIFFERENTACCOUNTS = 'ToDifferentAccounts'

    DIVISIONDEPENDENT = 'DivisionDependent'
