# -*- coding: utf-8 -*-

"""
lispublicservices

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class CustomPrintBaseEnum(object):

    """Implementation of the 'CustomPrintBase' enum.

    TODO: type enum description here.

    Attributes:
        NONE: TODO: type description here.
        SHIPMENT: TODO: type description here.
        FREIGHTTRANSPORT: TODO: type description here.
        CONTACT: TODO: type description here.
        SSCC: TODO: type description here.
        VOUCHER: TODO: type description here.
        MEETING: TODO: type description here.
        LOADINGDEVICES: TODO: type description here.
        CORRESPONDENCE: TODO: type description here.
        MAIL: TODO: type description here.
        ATLIS: TODO: type description here.
        CPSORDER: TODO: type description here.
        CPSCALL: TODO: type description here.
        CPSSERVICE: TODO: type description here.
        POSITION: TODO: type description here.
        STAFF: TODO: type description here.
        DELIVERYNOTE: TODO: type description here.
        CPS: TODO: type description here.
        LEASE: TODO: type description here.
        DAMAGEMANAGEMENT: TODO: type description here.
        SERVICEORDER: TODO: type description here.
        AUTOMOTIVE: TODO: type description here.
        FMSVEHICLE: TODO: type description here.
        CUSTOMER: TODO: type description here.
        REPORTGROUP: TODO: type description here.

    """

    ENUM_NONE = 'None'

    SHIPMENT = 'Shipment'

    FREIGHTTRANSPORT = 'FreightTransport'

    CONTACT = 'Contact'

    SSCC = 'SSCC'

    VOUCHER = 'Voucher'

    MEETING = 'Meeting'

    LOADINGDEVICES = 'LoadingDevices'

    CORRESPONDENCE = 'Correspondence'

    MAIL = 'Mail'

    ATLIS = 'ATLIS'

    CPSORDER = 'CPSOrder'

    CPSCALL = 'CPSCall'

    CPSSERVICE = 'CPSService'

    POSITION = 'Position'

    STAFF = 'Staff'

    DELIVERYNOTE = 'DeliveryNote'

    CPS = 'CPS'

    LEASE = 'Lease'

    DAMAGEMANAGEMENT = 'DamageManagement'

    SERVICEORDER = 'ServiceOrder'

    AUTOMOTIVE = 'Automotive'

    FMSVEHICLE = 'FMSVehicle'

    CUSTOMER = 'Customer'

    REPORTGROUP = 'ReportGroup'
