# -*- coding: utf-8 -*-

"""
lispublicservices

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class DamageStateEnum(object):

    """Implementation of the 'DamageState' enum.

    Gets or sets DamageState.

    Attributes:
        NO: TODO: type description here.
        YES: TODO: type description here.
        CLEARED: TODO: type description here.

    """

    NO = 'No'

    YES = 'Yes'

    CLEARED = 'Cleared'
