# -*- coding: utf-8 -*-

"""
lispublicservices

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class DataSourceEnum(object):

    """Implementation of the 'DataSource' enum.

    Gets or sets DataSource.

    Attributes:
        NONE: TODO: type description here.
        MANUEL: TODO: type description here.
        AUTOMATIC: TODO: type description here.
        EDI: TODO: type description here.
        WEBSPEDMANUAL: TODO: type description here.
        SCRIPT: TODO: type description here.
        PUBLICSERVICES: TODO: type description here.

    """

    ENUM_NONE = 'None'

    MANUEL = 'Manuel'

    AUTOMATIC = 'Automatic'

    EDI = 'EDI'

    WEBSPEDMANUAL = 'WebSpedManual'

    SCRIPT = 'Script'

    PUBLICSERVICES = 'PublicServices'
