# -*- coding: utf-8 -*-

"""
lispublicservices

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class DeleteStateEnum(object):

    """Implementation of the 'DeleteState' enum.

    Gets or sets DeleteState.

    Attributes:
        NOTSET: TODO: type description here.
        SHOULDBEDELETED: TODO: type description here.
        DELETED: TODO: type description here.

    """

    NOTSET = 'NotSet'

    SHOULDBEDELETED = 'ShouldBeDeleted'

    DELETED = 'Deleted'
