# -*- coding: utf-8 -*-

"""
lispublicservices

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class DepartureTypeEnum(object):

    """Implementation of the 'DepartureType' enum.

    Gets or sets DepartureType.

    Attributes:
        NONE: TODO: type description here.
        PRECOLLECTION: TODO: type description here.
        COLLECTION: TODO: type description here.
        RETRIEVAL: TODO: type description here.
        WAREHOUSE: TODO: type description here.
        PARTNERPRECOLLECTION: TODO: type description here.
        FULLLOAD: TODO: type description here.

    """

    ENUM_NONE = 'None'

    PRECOLLECTION = 'PreCollection'

    COLLECTION = 'Collection'

    RETRIEVAL = 'Retrieval'

    WAREHOUSE = 'Warehouse'

    PARTNERPRECOLLECTION = 'PartnerPreCollection'

    FULLLOAD = 'FullLoad'
