# -*- coding: utf-8 -*-

"""
lispublicservices

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class DestinationForwarderConditionTypeEnum(object):

    """Implementation of the 'DestinationForwarderConditionType' enum.

    Gets or sets the DestinationForwarderConditionType property. This property
    depends on the database field ESKond.

    Attributes:
        NOTSET: TODO: type description here.
        MANUAL: TODO: type description here.
        MASTERDATA: TODO: type description here.
        COMMON: TODO: type description here.
        POSITION: TODO: type description here.
        DEBKRE: TODO: type description here.
        DEBKREWAV: TODO: type description here.

    """

    NOTSET = 'NotSet'

    MANUAL = 'Manual'

    MASTERDATA = 'Masterdata'

    COMMON = 'Common'

    POSITION = 'Position'

    DEBKRE = 'DEBKRE'

    DEBKREWAV = 'DEBKREWAV'
