# -*- coding: utf-8 -*-

"""
lispublicservices

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class DisposalObservationEnum(object):

    """Implementation of the 'DisposalObservation' enum.

    Gets or sets DisposalObservation.

    Attributes:
        NONE: TODO: type description here.
        WASTE: TODO: type description here.
        OBSERVATION: TODO: type description here.
        SPECIAL: TODO: type description here.

    """

    ENUM_NONE = 'None'

    WASTE = 'Waste'

    OBSERVATION = 'Observation'

    SPECIAL = 'Special'
