# -*- coding: utf-8 -*-

"""
lispublicservices

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class DistanceCalculationMethodOrder1Enum(object):

    """Implementation of the 'DistanceCalculationMethodOrder1' enum.

    Gets or sets the distance calculation method order1.

    Attributes:
        NOTSET: TODO: type description here.
        NODE: TODO: type description here.
        GEOCOORDINATE: TODO: type description here.
        LINEARDISTANCE: TODO: type description here.
        DISTANCEROADWORK: TODO: type description here.
        DISTANCEROADWORKOLD: TODO: type description here.
        DIRECT: TODO: type description here.
        ROUTING: TODO: type description here.
        PTVMAPSERVER: TODO: type description here.
        PTVXSERVER: TODO: type description here.
        PTVCONTROLS: TODO: type description here.
        MAPPOINT: TODO: type description here.
        MAPPOINTZIP: TODO: type description here.
        CAROLA: TODO: type description here.
        MAP24: TODO: type description here.
        CANCEL: TODO: type description here.
        ASTAG: TODO: type description here.
        ASTAGOLD: TODO: type description here.

    """

    NOTSET = 'NotSet'

    NODE = 'Node'

    GEOCOORDINATE = 'GeoCoordinate'

    LINEARDISTANCE = 'LinearDistance'

    DISTANCEROADWORK = 'DistanceRoadWork'

    DISTANCEROADWORKOLD = 'DistanceRoadWorkOld'

    DIRECT = 'Direct'

    ROUTING = 'Routing'

    PTVMAPSERVER = 'PTVMapServer'

    PTVXSERVER = 'PTVXServer'

    PTVCONTROLS = 'PTVControls'

    MAPPOINT = 'MapPoint'

    MAPPOINTZIP = 'MapPointZip'

    CAROLA = 'Carola'

    MAP24 = 'Map24'

    CANCEL = 'Cancel'

    ASTAG = 'Astag'

    ASTAGOLD = 'AstagOld'
