# -*- coding: utf-8 -*-

"""
lispublicservices

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class DistanceStateEnum(object):

    """Implementation of the 'DistanceState' enum.

    Gets or sets the DistanceState property. This property depends on the
    database field KMStatus.

    Attributes:
        NOTSET: TODO: type description here.
        NO: TODO: type description here.
        AUTOMATIC: TODO: type description here.
        MANUALLY: TODO: type description here.
        DONOTCALCULATE: TODO: type description here.

    """

    NOTSET = 'NotSet'

    NO = 'No'

    AUTOMATIC = 'Automatic'

    MANUALLY = 'Manually'

    DONOTCALCULATE = 'DoNotCalculate'
