# -*- coding: utf-8 -*-

"""
lispublicservices

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class EcologicalMenace1Enum(object):

    """Implementation of the 'EcologicalMenace1' enum.

    Gets or sets the ecological menace.

    Attributes:
        NO: TODO: type description here.
        YES: TODO: type description here.

    """

    NO = 'No'

    YES = 'Yes'
