# -*- coding: utf-8 -*-

"""
lispublicservices

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class EdiStatusEnum(object):

    """Implementation of the 'EdiStatus' enum.

    Gets or sets EDIStatus.

    Attributes:
        NONE: TODO: type description here.
        ISNOTSEND: TODO: type description here.
        DOSEND: TODO: type description here.
        DONOTSEND: TODO: type description here.
        ISSEND: TODO: type description here.
        ISREVEIVED: TODO: type description here.
        NOTSENDTWICESTATUS: TODO: type description here.
        NOTSENDMANUALORDER: TODO: type description here.
        DOSENDINPREPARATION: TODO: type description here.
        ARCHIVED: TODO: type description here.

    """

    ENUM_NONE = 'None'

    ISNOTSEND = 'IsNotSend'

    DOSEND = 'DoSend'

    DONOTSEND = 'DoNotSend'

    ISSEND = 'IsSend'

    ISREVEIVED = 'IsReveived'

    NOTSENDTWICESTATUS = 'NotSendTwiceStatus'

    NOTSENDMANUALORDER = 'NotSendManualOrder'

    DOSENDINPREPARATION = 'DoSendInPreparation'

    ARCHIVED = 'Archived'
