# -*- coding: utf-8 -*-

"""
lispublicservices

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class EventType2Enum(object):

    """Implementation of the 'eventType2' enum.

    TODO: type enum description here.

    Attributes:
        NOTSET: TODO: type description here.
        WMS_CONSOLIDATESTOCKSISALLOWED: TODO: type description here.
        WMS_SWITCHLOCATIONISALLOWED: TODO: type description here.
        WMS_GOODSRECEIVECHECKBARCODE: TODO: type description here.
        WMS_CONSOLIDATIONONLOCATIONISALLOWED: TODO: type description here.

    """

    NOTSET = 'NotSet'

    WMS_CONSOLIDATESTOCKSISALLOWED = 'WMS_ConsolidateStocksIsAllowed'

    WMS_SWITCHLOCATIONISALLOWED = 'WMS_SwitchLocationIsAllowed'

    WMS_GOODSRECEIVECHECKBARCODE = 'WMS_GoodsReceiveCheckBarcode'

    WMS_CONSOLIDATIONONLOCATIONISALLOWED = 'WMS_ConsolidationOnLocationIsAllowed'
