# -*- coding: utf-8 -*-

"""
lispublicservices

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class FileTypeEnum(object):

    """Implementation of the 'FileType' enum.

    Gets or sets the type of the file.

    Attributes:
        NOTSET: TODO: type description here.
        PDF: TODO: type description here.
        WORD: TODO: type description here.
        EXCEL: TODO: type description here.
        TEXT: TODO: type description here.
        PICTURE: TODO: type description here.

    """

    NOTSET = 'NotSet'

    PDF = 'PDF'

    WORD = 'Word'

    EXCEL = 'Excel'

    TEXT = 'Text'

    PICTURE = 'Picture'
