# -*- coding: utf-8 -*-

"""
lispublicservices

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class FillTypeEnum(object):

    """Implementation of the 'FillType' enum.

    Gets or sets the TFuellTyp property. This property depends on the database
    field TFuellTyp.

    Attributes:
        NOTSET: TODO: type description here.
        BYRELATION: TODO: type description here.
        BYBORDEROINFO: TODO: type description here.
        BYCONSIGNEE: TODO: type description here.
        BYFINALRECIPIENTRELATION: TODO: type description here.
        BYTIMETABLE: TODO: type description here.
        NONE: TODO: type description here.

    """

    NOTSET = 'NotSet'

    BYRELATION = 'ByRelation'

    BYBORDEROINFO = 'ByBorderoInfo'

    BYCONSIGNEE = 'ByConsignee'

    BYFINALRECIPIENTRELATION = 'ByFinalRecipientRelation'

    BYTIMETABLE = 'ByTimeTable'

    ENUM_NONE = 'None'
