# -*- coding: utf-8 -*-

"""
lispublicservices

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class FreightPayerMainCarriageEnum(object):

    """Implementation of the 'FreightPayerMainCarriage' enum.

    Gets or sets FreightPayerMainCarriage.

    Attributes:
        NOTSET: TODO: type description here.
        LOADING: TODO: type description here.
        DELIVERY: TODO: type description here.
        BOTH: TODO: type description here.

    """

    NOTSET = 'NotSet'

    LOADING = 'Loading'

    DELIVERY = 'Delivery'

    BOTH = 'Both'
