# -*- coding: utf-8 -*-

"""
lispublicservices

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class GrantedByTypeEnum(object):

    """Implementation of the 'GrantedByType' enum.

    Gets or sets the type of the granted by.

    Attributes:
        USER: TODO: type description here.
        GROUP: TODO: type description here.

    """

    USER = 'User'

    GROUP = 'Group'
