# -*- coding: utf-8 -*-

"""
lispublicservices

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class InAdvanceRouteModeEnum(object):

    """Implementation of the 'InAdvanceRouteMode' enum.

    Gets or sets the in advance route mode.

    Attributes:
        DEFAULT: TODO: type description here.
        DESTINATIONFORWARDERORDELIVERYDEPOT: TODO: type description here.
        BORDEROUNLOADINGPOINTTODESTINATIONFORWARDERTOCONSIGNEE: TODO: type
            description here.

    """

    DEFAULT = 'Default'

    DESTINATIONFORWARDERORDELIVERYDEPOT = 'DestinationForwarderOrDeliveryDepot'

    BORDEROUNLOADINGPOINTTODESTINATIONFORWARDERTOCONSIGNEE = 'BorderoUnloadingPointToDestinationForwarderToConsignee'
