# -*- coding: utf-8 -*-

"""
lispublicservices

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class InvoicePreviewTypeEnum(object):

    """Implementation of the 'InvoicePreviewType' enum.

    TODO: type enum description here.

    Attributes:
        NONE: TODO: type description here.
        INVOICEPREVIEW: TODO: type description here.
        INVOICEREVIEW: TODO: type description here.
        INVOICEAPPROVAL: TODO: type description here.

    """

    ENUM_NONE = 'None'

    INVOICEPREVIEW = 'InvoicePreview'

    INVOICEREVIEW = 'InvoiceReview'

    INVOICEAPPROVAL = 'InvoiceApproval'
