# -*- coding: utf-8 -*-

"""
lispublicservices

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class InvoiceSideEnum(object):

    """Implementation of the 'InvoiceSide' enum.

    Gets or sets InvoiceSide.

    Attributes:
        ANY: TODO: type description here.
        DEBITSIDE: TODO: type description here.
        CREDITSIDE: TODO: type description here.

    """

    ANY = 'Any'

    DEBITSIDE = 'DebitSide'

    CREDITSIDE = 'CreditSide'
