# -*- coding: utf-8 -*-

"""
lispublicservices

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""
from lispublicservices.api_helper import APIHelper


class LISPublicOrderStatusHistory(object):

    """Implementation of the 'LISPublicOrderStatusHistory' model.

    The LISOrderStatusHistory data contract.

    Attributes:
        order_item (int): Gets or sets OrderItem.
        order_status_history_id (int): Gets or sets OrderStatusHistoryId.
        order_id (int): Gets or sets OrderId.
        order_no (int): Gets or sets OrderNo.
        order_status_id (int): Gets or sets OrderStatusId.
        difference_quantity (int): Gets or sets DifferenceQuantity.
        difference_unit (string): Gets or sets DifferenceUnit.
        note (string): Gets or sets Note.
        changed_on (datetime): Gets or sets ChangedOn.
        changed_by (string): Gets or sets ChangedBy.
        event_date (datetime): Gets or sets EventDate.
        event_time (datetime): Gets or sets EventTime.
        edi_status (EdiStatusEnum): Gets or sets EDIStatus.
        data_source (DataSourceEnum): Gets or sets DataSource.
        generated_internal_no (int): Gets or sets GeneratedInternalNo.
        carrier_id (int): Gets or sets CarrierId.
        tour_id (int): Gets or sets TourId.
        tour_no (int): Gets or sets TourNo.
        special_invoicing_id (int): Gets or sets SpecialInvoicingId.
        receipt (string): Gets or sets Receipt.
        created_by (string): Gets or sets CreatedBy.
        created_on (datetime): Gets or sets CreatedOn.
        bordero_id (int): Gets or sets BorderoId.
        course (string): Gets or sets Course.
        mtype (Type2Enum): Gets or sets the type.
        status_history_id (int): Gets or sets the status history id.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "order_item": 'orderItem',
        "order_status_history_id": 'orderStatusHistoryId',
        "order_id": 'orderId',
        "order_no": 'orderNo',
        "order_status_id": 'orderStatusId',
        "difference_quantity": 'differenceQuantity',
        "difference_unit": 'differenceUnit',
        "note": 'note',
        "changed_on": 'changedOn',
        "changed_by": 'changedBy',
        "event_date": 'eventDate',
        "event_time": 'eventTime',
        "edi_status": 'ediStatus',
        "data_source": 'dataSource',
        "generated_internal_no": 'generatedInternalNo',
        "carrier_id": 'carrierId',
        "tour_id": 'tourId',
        "tour_no": 'tourNo',
        "special_invoicing_id": 'specialInvoicingId',
        "receipt": 'receipt',
        "created_by": 'createdBy',
        "created_on": 'createdOn',
        "bordero_id": 'borderoId',
        "course": 'course',
        "mtype": 'type',
        "status_history_id": 'statusHistoryId'
    }

    _optionals = [
        'order_item',
        'order_status_history_id',
        'order_id',
        'order_no',
        'order_status_id',
        'difference_quantity',
        'difference_unit',
        'note',
        'changed_on',
        'changed_by',
        'event_date',
        'event_time',
        'edi_status',
        'data_source',
        'generated_internal_no',
        'carrier_id',
        'tour_id',
        'tour_no',
        'special_invoicing_id',
        'receipt',
        'created_by',
        'created_on',
        'bordero_id',
        'course',
        'mtype',
        'status_history_id',
    ]

    def __init__(self,
                 order_item=APIHelper.SKIP,
                 order_status_history_id=APIHelper.SKIP,
                 order_id=APIHelper.SKIP,
                 order_no=APIHelper.SKIP,
                 order_status_id=APIHelper.SKIP,
                 difference_quantity=APIHelper.SKIP,
                 difference_unit=APIHelper.SKIP,
                 note=APIHelper.SKIP,
                 changed_on=APIHelper.SKIP,
                 changed_by=APIHelper.SKIP,
                 event_date=APIHelper.SKIP,
                 event_time=APIHelper.SKIP,
                 edi_status=APIHelper.SKIP,
                 data_source=APIHelper.SKIP,
                 generated_internal_no=APIHelper.SKIP,
                 carrier_id=APIHelper.SKIP,
                 tour_id=APIHelper.SKIP,
                 tour_no=APIHelper.SKIP,
                 special_invoicing_id=APIHelper.SKIP,
                 receipt=APIHelper.SKIP,
                 created_by=APIHelper.SKIP,
                 created_on=APIHelper.SKIP,
                 bordero_id=APIHelper.SKIP,
                 course=APIHelper.SKIP,
                 mtype=APIHelper.SKIP,
                 status_history_id=APIHelper.SKIP):
        """Constructor for the LISPublicOrderStatusHistory class"""

        # Initialize members of the class
        if order_item is not APIHelper.SKIP:
            self.order_item = order_item 
        if order_status_history_id is not APIHelper.SKIP:
            self.order_status_history_id = order_status_history_id 
        if order_id is not APIHelper.SKIP:
            self.order_id = order_id 
        if order_no is not APIHelper.SKIP:
            self.order_no = order_no 
        if order_status_id is not APIHelper.SKIP:
            self.order_status_id = order_status_id 
        if difference_quantity is not APIHelper.SKIP:
            self.difference_quantity = difference_quantity 
        if difference_unit is not APIHelper.SKIP:
            self.difference_unit = difference_unit 
        if note is not APIHelper.SKIP:
            self.note = note 
        if changed_on is not APIHelper.SKIP:
            self.changed_on = APIHelper.RFC3339DateTime(changed_on) if changed_on else None 
        if changed_by is not APIHelper.SKIP:
            self.changed_by = changed_by 
        if event_date is not APIHelper.SKIP:
            self.event_date = APIHelper.RFC3339DateTime(event_date) if event_date else None 
        if event_time is not APIHelper.SKIP:
            self.event_time = APIHelper.RFC3339DateTime(event_time) if event_time else None 
        if edi_status is not APIHelper.SKIP:
            self.edi_status = edi_status 
        if data_source is not APIHelper.SKIP:
            self.data_source = data_source 
        if generated_internal_no is not APIHelper.SKIP:
            self.generated_internal_no = generated_internal_no 
        if carrier_id is not APIHelper.SKIP:
            self.carrier_id = carrier_id 
        if tour_id is not APIHelper.SKIP:
            self.tour_id = tour_id 
        if tour_no is not APIHelper.SKIP:
            self.tour_no = tour_no 
        if special_invoicing_id is not APIHelper.SKIP:
            self.special_invoicing_id = special_invoicing_id 
        if receipt is not APIHelper.SKIP:
            self.receipt = receipt 
        if created_by is not APIHelper.SKIP:
            self.created_by = created_by 
        if created_on is not APIHelper.SKIP:
            self.created_on = APIHelper.RFC3339DateTime(created_on) if created_on else None 
        if bordero_id is not APIHelper.SKIP:
            self.bordero_id = bordero_id 
        if course is not APIHelper.SKIP:
            self.course = course 
        if mtype is not APIHelper.SKIP:
            self.mtype = mtype 
        if status_history_id is not APIHelper.SKIP:
            self.status_history_id = status_history_id 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary

        order_item = dictionary.get("orderItem") if dictionary.get("orderItem") else APIHelper.SKIP
        order_status_history_id = dictionary.get("orderStatusHistoryId") if dictionary.get("orderStatusHistoryId") else APIHelper.SKIP
        order_id = dictionary.get("orderId") if dictionary.get("orderId") else APIHelper.SKIP
        order_no = dictionary.get("orderNo") if dictionary.get("orderNo") else APIHelper.SKIP
        order_status_id = dictionary.get("orderStatusId") if dictionary.get("orderStatusId") else APIHelper.SKIP
        difference_quantity = dictionary.get("differenceQuantity") if dictionary.get("differenceQuantity") else APIHelper.SKIP
        difference_unit = dictionary.get("differenceUnit") if dictionary.get("differenceUnit") else APIHelper.SKIP
        note = dictionary.get("note") if dictionary.get("note") else APIHelper.SKIP
        changed_on = APIHelper.RFC3339DateTime.from_value(dictionary.get("changedOn")).datetime if dictionary.get("changedOn") else APIHelper.SKIP
        changed_by = dictionary.get("changedBy") if dictionary.get("changedBy") else APIHelper.SKIP
        event_date = APIHelper.RFC3339DateTime.from_value(dictionary.get("eventDate")).datetime if dictionary.get("eventDate") else APIHelper.SKIP
        event_time = APIHelper.RFC3339DateTime.from_value(dictionary.get("eventTime")).datetime if dictionary.get("eventTime") else APIHelper.SKIP
        edi_status = dictionary.get("ediStatus") if dictionary.get("ediStatus") else APIHelper.SKIP
        data_source = dictionary.get("dataSource") if dictionary.get("dataSource") else APIHelper.SKIP
        generated_internal_no = dictionary.get("generatedInternalNo") if dictionary.get("generatedInternalNo") else APIHelper.SKIP
        carrier_id = dictionary.get("carrierId") if dictionary.get("carrierId") else APIHelper.SKIP
        tour_id = dictionary.get("tourId") if dictionary.get("tourId") else APIHelper.SKIP
        tour_no = dictionary.get("tourNo") if dictionary.get("tourNo") else APIHelper.SKIP
        special_invoicing_id = dictionary.get("specialInvoicingId") if dictionary.get("specialInvoicingId") else APIHelper.SKIP
        receipt = dictionary.get("receipt") if dictionary.get("receipt") else APIHelper.SKIP
        created_by = dictionary.get("createdBy") if dictionary.get("createdBy") else APIHelper.SKIP
        created_on = APIHelper.RFC3339DateTime.from_value(dictionary.get("createdOn")).datetime if dictionary.get("createdOn") else APIHelper.SKIP
        bordero_id = dictionary.get("borderoId") if dictionary.get("borderoId") else APIHelper.SKIP
        course = dictionary.get("course") if dictionary.get("course") else APIHelper.SKIP
        mtype = dictionary.get("type") if dictionary.get("type") else APIHelper.SKIP
        status_history_id = dictionary.get("statusHistoryId") if dictionary.get("statusHistoryId") else APIHelper.SKIP
        # Return an object of this model
        return cls(order_item,
                   order_status_history_id,
                   order_id,
                   order_no,
                   order_status_id,
                   difference_quantity,
                   difference_unit,
                   note,
                   changed_on,
                   changed_by,
                   event_date,
                   event_time,
                   edi_status,
                   data_source,
                   generated_internal_no,
                   carrier_id,
                   tour_id,
                   tour_no,
                   special_invoicing_id,
                   receipt,
                   created_by,
                   created_on,
                   bordero_id,
                   course,
                   mtype,
                   status_history_id)
