# -*- coding: utf-8 -*-

"""
lispublicservices

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class LisDataTypeEnum(object):

    """Implementation of the 'LisDataType' enum.

    Gets or sets the LIS data type of this instance represents.

    Attributes:
        UNSUPPORTED: TODO: type description here.
        INT32: TODO: type description here.
        DATE: TODO: type description here.
        INT16: TODO: type description here.
        DOUBLE: TODO: type description here.
        DECIMAL: TODO: type description here.
        STRING: TODO: type description here.
        CURRENCY: TODO: type description here.
        TIME: TODO: type description here.
        DATETIME: TODO: type description here.
        CUSTOM: TODO: type description here.

    """

    UNSUPPORTED = 'Unsupported'

    INT32 = 'Int32'

    DATE = 'Date'

    INT16 = 'Int16'

    DOUBLE = 'Double'

    DECIMAL = 'Decimal'

    STRING = 'String'

    CURRENCY = 'Currency'

    TIME = 'Time'

    DATETIME = 'DateTime'

    CUSTOM = 'Custom'
