# -*- coding: utf-8 -*-

"""
lispublicservices

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""
from lispublicservices.api_helper import APIHelper


class LISPublicOrderLongText(object):

    """Implementation of the 'LISPublicOrderLongText' model.

    The LISOrderLongText data contract.

    Attributes:
        text_class (int): Gets or sets TextType.
        text (string): Gets or sets Text.
        order_id (int): Gets or sets OrderId.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "text_class": 'textClass',
        "text": 'text',
        "order_id": 'orderId'
    }

    _optionals = [
        'text_class',
        'text',
        'order_id',
    ]

    def __init__(self,
                 text_class=APIHelper.SKIP,
                 text=APIHelper.SKIP,
                 order_id=APIHelper.SKIP):
        """Constructor for the LISPublicOrderLongText class"""

        # Initialize members of the class
        if text_class is not APIHelper.SKIP:
            self.text_class = text_class 
        if text is not APIHelper.SKIP:
            self.text = text 
        if order_id is not APIHelper.SKIP:
            self.order_id = order_id 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary

        text_class = dictionary.get("textClass") if dictionary.get("textClass") else APIHelper.SKIP
        text = dictionary.get("text") if dictionary.get("text") else APIHelper.SKIP
        order_id = dictionary.get("orderId") if dictionary.get("orderId") else APIHelper.SKIP
        # Return an object of this model
        return cls(text_class,
                   text,
                   order_id)
