# -*- coding: utf-8 -*-

"""
lispublicservices

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""
from lispublicservices.api_helper import APIHelper


class LISPublicOrderLumpSum(object):

    """Implementation of the 'LISPublicOrderLumpSum' model.

    The LISOrderLumpSum data contract.

    Attributes:
        amount (float): Gets or sets Amount.
        currency (string): Gets or sets Currency.
        price_per (int): Gets or sets PricePer.
        value (float): Gets or sets Value.
        sales_tax_code (string): Gets or sets SalesTaxCode.
        charge_id (int): Gets or sets ChargeId.
        charge_description (string): Gets or sets ChargeDescription.
        cash_discount (bool): Gets or sets a value indicating whether [cash
            discount].

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "amount": 'amount',
        "currency": 'currency',
        "price_per": 'pricePer',
        "value": 'value',
        "sales_tax_code": 'salesTaxCode',
        "charge_id": 'chargeId',
        "charge_description": 'chargeDescription',
        "cash_discount": 'cashDiscount'
    }

    _optionals = [
        'amount',
        'currency',
        'price_per',
        'value',
        'sales_tax_code',
        'charge_id',
        'charge_description',
        'cash_discount',
    ]

    def __init__(self,
                 amount=APIHelper.SKIP,
                 currency=APIHelper.SKIP,
                 price_per=APIHelper.SKIP,
                 value=APIHelper.SKIP,
                 sales_tax_code=APIHelper.SKIP,
                 charge_id=APIHelper.SKIP,
                 charge_description=APIHelper.SKIP,
                 cash_discount=APIHelper.SKIP):
        """Constructor for the LISPublicOrderLumpSum class"""

        # Initialize members of the class
        if amount is not APIHelper.SKIP:
            self.amount = amount 
        if currency is not APIHelper.SKIP:
            self.currency = currency 
        if price_per is not APIHelper.SKIP:
            self.price_per = price_per 
        if value is not APIHelper.SKIP:
            self.value = value 
        if sales_tax_code is not APIHelper.SKIP:
            self.sales_tax_code = sales_tax_code 
        if charge_id is not APIHelper.SKIP:
            self.charge_id = charge_id 
        if charge_description is not APIHelper.SKIP:
            self.charge_description = charge_description 
        if cash_discount is not APIHelper.SKIP:
            self.cash_discount = cash_discount 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary

        amount = dictionary.get("amount") if dictionary.get("amount") else APIHelper.SKIP
        currency = dictionary.get("currency") if dictionary.get("currency") else APIHelper.SKIP
        price_per = dictionary.get("pricePer") if dictionary.get("pricePer") else APIHelper.SKIP
        value = dictionary.get("value") if dictionary.get("value") else APIHelper.SKIP
        sales_tax_code = dictionary.get("salesTaxCode") if dictionary.get("salesTaxCode") else APIHelper.SKIP
        charge_id = dictionary.get("chargeId") if dictionary.get("chargeId") else APIHelper.SKIP
        charge_description = dictionary.get("chargeDescription") if dictionary.get("chargeDescription") else APIHelper.SKIP
        cash_discount = dictionary.get("cashDiscount") if "cashDiscount" in dictionary.keys() else APIHelper.SKIP
        # Return an object of this model
        return cls(amount,
                   currency,
                   price_per,
                   value,
                   sales_tax_code,
                   charge_id,
                   charge_description,
                   cash_discount)
