# -*- coding: utf-8 -*-

"""
lispublicservices

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""
from lispublicservices.api_helper import APIHelper


class LISPublicOrderInformation(object):

    """Implementation of the 'LISPublicOrderInformation' model.

    LISPublicOrderInformation

    Attributes:
        no (int): Gets or sets the no.
        text_id (int): Gets or sets the text id.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "no": 'no',
        "text_id": 'textId'
    }

    _optionals = [
        'no',
        'text_id',
    ]

    def __init__(self,
                 no=APIHelper.SKIP,
                 text_id=APIHelper.SKIP):
        """Constructor for the LISPublicOrderInformation class"""

        # Initialize members of the class
        if no is not APIHelper.SKIP:
            self.no = no 
        if text_id is not APIHelper.SKIP:
            self.text_id = text_id 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary

        no = dictionary.get("no") if dictionary.get("no") else APIHelper.SKIP
        text_id = dictionary.get("textId") if dictionary.get("textId") else APIHelper.SKIP
        # Return an object of this model
        return cls(no,
                   text_id)
