# -*- coding: utf-8 -*-

"""
lispublicservices

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""
from lispublicservices.api_helper import APIHelper


class LISSpecialInvoiceOptions(object):

    """Implementation of the 'LISSpecialInvoiceOptions' model.

    Options to create a special invoice

    Attributes:
        book_incoming_vouchers (bool): Book incoming vouchers

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "book_incoming_vouchers": 'bookIncomingVouchers'
    }

    _optionals = [
        'book_incoming_vouchers',
    ]

    def __init__(self,
                 book_incoming_vouchers=APIHelper.SKIP):
        """Constructor for the LISSpecialInvoiceOptions class"""

        # Initialize members of the class
        if book_incoming_vouchers is not APIHelper.SKIP:
            self.book_incoming_vouchers = book_incoming_vouchers 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary

        book_incoming_vouchers = dictionary.get("bookIncomingVouchers") if "bookIncomingVouchers" in dictionary.keys() else APIHelper.SKIP
        # Return an object of this model
        return cls(book_incoming_vouchers)
