# -*- coding: utf-8 -*-

"""
lispublicservices

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class LoadingTypeEnum(object):

    """Implementation of the 'LoadingType' enum.

    Gets or sets the type of the loading.

    Attributes:
        LOADING: TODO: type description here.
        DELIVERY: TODO: type description here.

    """

    LOADING = 'Loading'

    DELIVERY = 'Delivery'
