# -*- coding: utf-8 -*-

"""
lispublicservices

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class LoadDevCreditingAccountEnum(object):

    """Implementation of the 'LoadDevCreditingAccount' enum.

    Gets or sets the load dev crediting account.

    Attributes:
        NOTSET: TODO: type description here.
        FORWARDER: TODO: type description here.
        DESPATCHER: TODO: type description here.
        CUSTOMER: TODO: type description here.
        PRIMARYDESPATCHER: TODO: type description here.
        NOBOOKING: TODO: type description here.

    """

    NOTSET = 'NotSet'

    FORWARDER = 'Forwarder'

    DESPATCHER = 'Despatcher'

    CUSTOMER = 'Customer'

    PRIMARYDESPATCHER = 'PrimaryDespatcher'

    NOBOOKING = 'NoBooking'
