# -*- coding: utf-8 -*-

"""
lispublicservices

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class LoadDevFortrasIdEnum(object):

    """Implementation of the 'LoadDevFortrasId' enum.

    Gets or sets the load dev fortras id.

    Attributes:
        NOTSET: TODO: type description here.
        NOFORTRASRELEVANCE: TODO: type description here.
        EUROFLATPALLET: TODO: type description here.
        PALLETCAGE: TODO: type description here.

    """

    NOTSET = 'NotSet'

    NOFORTRASRELEVANCE = 'NoFortrasRelevance'

    EUROFLATPALLET = 'EuroFlatPallet'

    PALLETCAGE = 'PalletCage'
