# -*- coding: utf-8 -*-

"""
lispublicservices

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class LockStatusEnum(object):

    """Implementation of the 'LockStatus' enum.

    Gets or sets the lock status.

    Attributes:
        NOTSET: TODO: type description here.
        LOCKED: TODO: type description here.
        UNLOCKED: TODO: type description here.

    """

    NOTSET = 'NotSet'

    LOCKED = 'Locked'

    UNLOCKED = 'Unlocked'
