# -*- coding: utf-8 -*-

"""
lispublicservices

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class OrderInformationActivityEnum(object):

    """Implementation of the 'OrderInformationActivity' enum.

    Gets or sets OrderInformationActivity.

    Attributes:
        SETDISPATCHNOTE: TODO: type description here.
        DELETEDISPATCHNOTE: TODO: type description here.

    """

    SETDISPATCHNOTE = 'SetDispatchNote'

    DELETEDISPATCHNOTE = 'DeleteDispatchNote'
