# -*- coding: utf-8 -*-

"""
lispublicservices

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class OrderInputType1Enum(object):

    """Implementation of the 'OrderInputType1' enum.

    Gets or sets OrderInputType.

    Attributes:
        NOTSET: TODO: type description here.
        OUTGOING: TODO: type description here.
        OUTGOINGPRIORCOLLECTION: TODO: type description here.
        OUTGOINGPARTNERPRIORCOLLECTION: TODO: type description here.
        INCOMING: TODO: type description here.
        INCOMINGLOGISTICPROVIDER: TODO: type description here.
        INCOMINGDELIVERY: TODO: type description here.
        INCOMINGPRIORCOLLECTION: TODO: type description here.
        BORDEROCOLLECT: TODO: type description here.
        BORDEROFORWARD: TODO: type description here.
        BORDERO: TODO: type description here.
        HUBBORDERO_DEFAULT: TODO: type description here.
        HUBBORDERO_HUB: TODO: type description here.
        DEPOTBORDERO: TODO: type description here.
        CONSIGNEEBORDERO: TODO: type description here.
        DRIVINGROUTE: TODO: type description here.

    """

    NOTSET = 'NotSet'

    OUTGOING = 'Outgoing'

    OUTGOINGPRIORCOLLECTION = 'OutgoingPriorCollection'

    OUTGOINGPARTNERPRIORCOLLECTION = 'OutgoingPartnerPriorCollection'

    INCOMING = 'Incoming'

    INCOMINGLOGISTICPROVIDER = 'IncomingLogisticProvider'

    INCOMINGDELIVERY = 'IncomingDelivery'

    INCOMINGPRIORCOLLECTION = 'IncomingPriorCollection'

    BORDEROCOLLECT = 'BorderoCollect'

    BORDEROFORWARD = 'BorderoForward'

    BORDERO = 'Bordero'

    HUBBORDERO_DEFAULT = 'HubBordero_Default'

    HUBBORDERO_HUB = 'HubBordero_Hub'

    DEPOTBORDERO = 'DepotBordero'

    CONSIGNEEBORDERO = 'ConsigneeBordero'

    DRIVINGROUTE = 'DrivingRoute'
