# -*- coding: utf-8 -*-

"""
lispublicservices

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class PricePerEnum(object):

    """Implementation of the 'PricePer' enum.

    Gets or sets the price per.

    Attributes:
        NOTSET: TODO: type description here.
        KILO1000: TODO: type description here.
        CUBICDECIMETER: TODO: type description here.
        SQUAREMETER: TODO: type description here.
        QUANTITY: TODO: type description here.
        KILOMETER: TODO: type description here.
        LOADINGMETER: TODO: type description here.
        STORAGEPLACES: TODO: type description here.

    """

    NOTSET = 'NotSet'

    KILO1000 = 'Kilo1000'

    CUBICDECIMETER = 'CubicDecimeter'

    SQUAREMETER = 'SquareMeter'

    QUANTITY = 'Quantity'

    KILOMETER = 'Kilometer'

    LOADINGMETER = 'LoadingMeter'

    STORAGEPLACES = 'StoragePlaces'
