# -*- coding: utf-8 -*-

"""
lispublicservices

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class PrintActionEnum(object):

    """Implementation of the 'PrintAction' enum.

    TODO: type enum description here.

    Attributes:
        NONE: TODO: type description here.
        TEST: TODO: type description here.
        REPEAT: TODO: type description here.
        SHARP: TODO: type description here.

    """

    ENUM_NONE = 'None'

    TEST = 'Test'

    REPEAT = 'Repeat'

    SHARP = 'Sharp'
