# -*- coding: utf-8 -*-

"""
lispublicservices

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class SourceEnum(object):

    """Implementation of the 'Source' enum.

    Is it the middle of the locality?

    Attributes:
        NOTSET: TODO: type description here.
        MAP: TODO: type description here.

    """

    NOTSET = 'NotSet'

    MAP = 'Map'
