# -*- coding: utf-8 -*-

"""
lispublicservices

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class SpecialInvoiceKindEnum(object):

    """Implementation of the 'SpecialInvoiceKind' enum.

    Kind of the special invoice

    Attributes:
        NOTSET: TODO: type description here.
        OUTGOINGINVOICE: TODO: type description here.
        OUTGOINGCREDITVOUCHER: TODO: type description here.
        INCOMINGINVOICE: TODO: type description here.
        INCOMINGCREDITVOUCHER: TODO: type description here.

    """

    NOTSET = 'NotSet'

    OUTGOINGINVOICE = 'OutgoingInvoice'

    OUTGOINGCREDITVOUCHER = 'OutgoingCreditVoucher'

    INCOMINGINVOICE = 'IncomingInvoice'

    INCOMINGCREDITVOUCHER = 'IncomingCreditVoucher'
