# -*- coding: utf-8 -*-

"""
lispublicservices

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class StatusEventIdEnum(object):

    """Implementation of the 'StatusEventId' enum.

    Event Id of given status.

    Attributes:
        NONE: TODO: type description here.
        ORDERFROMEDI: TODO: type description here.
        ORDERFROMEDIWITHERROR: TODO: type description here.
        ORDERCREATED: TODO: type description here.
        TOURSHIPMENTASSIGNED: TODO: type description here.
        TOURSHIPMENTASSIGNEDBYSCANNING: TODO: type description here.
        TOURSHIPMENTRELEASED: TODO: type description here.
        TOURGENERATED: TODO: type description here.
        TOURGENERATEDWITHOPENLOADINGORDER: TODO: type description here.
        TOURDELETED: TODO: type description here.
        FUNCTIONSETLOADINGAPPOINTMENT: TODO: type description here.
        TOURTOARCHIV: TODO: type description here.
        ORDERCHANGED: TODO: type description here.
        ORDERCHANGEDWITHERROR: TODO: type description here.
        ORDERCHANGEDAUTOMATICALLY: TODO: type description here.
        ORDERCHANGEDFROMADVICETONORMAL: TODO: type description here.
        SHIPMENTCHANGEDFROMSCHEDULE: TODO: type description here.
        STATETOURPLANED: TODO: type description here.
        STATETOUROPEN: TODO: type description here.
        BORDEROCONFIRMED: TODO: type description here.
        BORDEROREMOVED: TODO: type description here.
        BORDEROCONFIRMEDALL: TODO: type description here.
        AUTOBOOKSUCCEEDED: TODO: type description here.
        AUTOBOOKFAILED: TODO: type description here.
        LDTRANSACTIONSAVED: TODO: type description here.
        LDTRANSACTIONBOOKED: TODO: type description here.
        LDTRANSACTIONDELETED: TODO: type description here.
        TOURFROMARCHIV: TODO: type description here.
        TOURBACKTODELIVERD: TODO: type description here.
        TOURBACKTODISPATCHED: TODO: type description here.
        ELISDONTUSEPLEASETRANSLATE_DFUE_AVIS_FERTIG: TODO: type description
            here.
        ORDERCHANGEDFROMUNCOMPLETETONORMAL: TODO: type description here.
        ORDERCREATEDINSPLITTING: TODO: type description here.
        ORDERDELETEDBYSPLITTING: TODO: type description here.
        ORDERSPLITDELETED: TODO: type description here.
        SSCCSPLITTING: TODO: type description here.
        LOCKEDINSPLITTING: TODO: type description here.
        ORDERISSPLITTET: TODO: type description here.
        ASSIGNEDTOBORDERO: TODO: type description here.
        RELEASEDFROMBORDERO: TODO: type description here.
        ELISDONTUSEPLEASETRANSLATE_GEAENDERT: TODO: type description here.
        ELISDONTUSEPLEASETRANSLATE_WA_GEBUCHT: TODO: type description here.
        LOADINGLISTPRINTED: TODO: type description here.
        BORDEROORROLLKARTEPRINTED: TODO: type description here.
        TOINTRANSIT: TODO: type description here.
        SHIPMENTSINTRANSIT: TODO: type description here.
        SHIPMENTSINTRANSITALL: TODO: type description here.
        ELISDONTUSEPLEASETRANSLATE_ZU_LL: TODO: type description here.
        ELISDONTUSEPLEASETRANSLATE_ZU_BORDERO: TODO: type description here.
        ELISDONTUSEPLEASETRANSLATE_ENTLADEBERICHT: TODO: type description
            here.
        ELISDONTUSEPLEASETRANSLATE_ENTLADEBERICHT_IMPORT: TODO: type
            description here.
        ELISDONTUSEPLEASETRANSLATE_ENTLADEBERICHT_IM_POSI: TODO: type
            description here.
        ELISDONTUSEPLEASETRANSLATE_ENTLADEBERICHT_EXPORT: TODO: type
            description here.
        DELETED: TODO: type description here.
        SPECIALINVOICEDELETED: TODO: type description here.
        ELISDONTUSEPLEASETRANSLATE_AUF_EXPORTIERT: TODO: type description
            here.
        ELISDONTUSEPLEASETRANSLATE_TOUR_EXPORTIERT: TODO: type description
            here.
        ELISDONTUSEPLEASETRANSLATE_RECADV_BESTAETIGT: TODO: type description
            here.
        ELISDONTUSEPLEASETRANSLATE_RECADV_ZURUECK_OFFEN: TODO: type
            description here.
        ELISDONTUSEPLEASETRANSLATE_RECADV_LEERGUT_ANLEGEN: TODO: type
            description here.
        ELISDONTUSEPLEASETRANSLATE_RECADV_LEERGUT_ANGELEGT: TODO: type
            description here.
        ELISDONTUSEPLEASETRANSLATE_RECADV_GESENDET: TODO: type description
            here.
        ELISDONTUSEPLEASETRANSLATE_RE_SCHARF_GEDRUCKT: TODO: type description
            here.
        ELISDONTUSEPLEASETRANSLATE_GS_SCHARF_GEDRUCKT: TODO: type description
            here.
        ELISDONTUSEPLEASETRANSLATE_RE_PROFORMA_GEDRUCKT: TODO: type
            description here.
        ELISDONTUSEPLEASETRANSLATE_GS_PROFORMA_GEDRUCKT: TODO: type
            description here.
        DEBITCALCULATIONCOMPLETED: TODO: type description here.
        DEBITCALCULATIONSKIPPED: TODO: type description here.
        CREDITCALCULATIONCOMPLETED: TODO: type description here.
        CREDITCALCULATIONSKIPPED: TODO: type description here.
        CHANGEDFREIGHTTERMTOINCOTERM: TODO: type description here.
        CHANGE_FREIGHTTERM_FOR_CALCSHIPMENT: TODO: type description here.
        ELISDONTUSEPLEASETRANSLATE_RE_EXPORTIERT: TODO: type description
            here.
        ELISDONTUSEPLEASETRANSLATE_GS_EXPORTIERT: TODO: type description
            here.
        ELISDONTUSEPLEASETRANSLATE_LD_OFFEN: TODO: type description here.
        ELISDONTUSEPLEASETRANSLATE_LD_DISPONIERT: TODO: type description
            here.
        ELISDONTUSEPLEASETRANSLATE_LD_UNTERWEGS: TODO: type description here.
        ELISDONTUSEPLEASETRANSLATE_LD_BESTAETIGT: TODO: type description
            here.
        ELISDONTUSEPLEASETRANSLATE_LD_UNTERTEILT: TODO: type description
            here.
        ELISDONTUSEPLEASETRANSLATE_LD_TEILGENERIERT: TODO: type description
            here.
        DEBITCALCULATIONCANCELED: TODO: type description here.
        DEBITINVOICECANCELED: TODO: type description here.
        CREDITCALCULATIONCANCELED: TODO: type description here.
        CREDITINVOICECANCELED: TODO: type description here.
        SHIPMENTLOCKUNLOCKED: TODO: type description here.
        TOUR_CABOTAGE_CONFLICT: TODO: type description here.
        TOUR_VEHICLELOCKAPPOINTMENT_CONFLICT: TODO: type description here.
        TOUR_GREENLICENCEPLATE_CONFLICT: TODO: type description here.
        TOUR_CABOTAGE_CLEARANCE: TODO: type description here.
        TOUR_VEHICLELOCKAPPOINTMENT_CLEARANCE: TODO: type description here.
        TOUR_GREENLICENCEPLATE_CLEARANCE: TODO: type description here.
        ELISDONTUSEPLEASETRANSLATE_KABOTAGE_FREIGABE: TODO: type description
            here.
        SHIPMENTCOMMITED: TODO: type description here.
        ORDERDELIVERED: TODO: type description here.
        ELISDONTUSEPLEASETRANSLATE_SDG_ABLIEFERUNG_OK: TODO: type description
            here.
        ELISDONTUSEPLEASETRANSLATE_SDG_ABLIEFERUNG_NICHT: TODO: type
            description here.
        SHIPMENTINTRANSIT: TODO: type description here.
        SHIPMENTINTRANSITTODESTINATIONFORWARDER: TODO: type description here.
        ELISDONTUSEPLEASETRANSLATE_SCC_MITDIFF: TODO: type description here.
        ELISDONTUSEPLEASETRANSLATE_SCC_FEHLEND: TODO: type description here.
        ELISDONTUSEPLEASETRANSLATE_SCC_UMDISPO: TODO: type description here.
        ELISDONTUSEPLEASETRANSLATE_SDG_KOMMISSIONIERT: TODO: type description
            here.
        SHIPMENTINBOUNDCOMPLETELYSCANNED: TODO: type description here.
        SHIPMENTINBOUNDPARTIALLYSCANNED: TODO: type description here.
        SHIPMENTINBOUNDNOTSCANNED: TODO: type description here.
        ELISDONTUSEPLEASETRANSLATE_SDG_AUTOENTFIX: TODO: type description
            here.
        SHIPMENTOUTBOUNDCOMPLETELYSCANNED: TODO: type description here.
        SHIPMENTOUTBOUNDPARTIALLYSCANNED: TODO: type description here.
        SHIPMENTOUTBOUNDNOTSCANNED: TODO: type description here.
        SHIPMENTLOADINGOK: TODO: type description here.
        SHIPMENTINBOUNDPARTIALLYDAMAGED: TODO: type description here.
        SHIPMENTINBOUNDNOTDAMAGED: TODO: type description here.
        SHIPMENTINBOUNDCOMPLETELYDAMAGED: TODO: type description here.
        SHIPMENTOUTBOUNDPARTIALLYDAMAGED: TODO: type description here.
        SHIPMENTOUTBOUNDNOTDAMAGED: TODO: type description here.
        SHIPMENTOUTBOUNDCOMPLETELYDAMAGED: TODO: type description here.
        SHIPMENTINBOUNDPARTIALLYANDDAMAGED: TODO: type description here.
        SHIPMENTOUTBOUNDPARTIALLYANDDAMAGED: TODO: type description here.
        ARCHIVEDDOCUMENTMANUALLY: TODO: type description here.
        ARCHIVEDDOCUMENTAUTOMATICALLY: TODO: type description here.
        ARCHIVEDDOCUMENTAUTOMATICALLYIMPORT: TODO: type description here.
        ELISDONTUSEPLEASETRANSLATE_VDISPO_SPERREN: TODO: type description
            here.
        ELISDONTUSEPLEASETRANSLATE_VDISPO_FREIGEBEN: TODO: type description
            here.
        ELISDONTUSEPLEASETRANSLATE_VDISPO_ADD: TODO: type description here.
        ELISDONTUSEPLEASETRANSLATE_VDISPO_REMOVE: TODO: type description
            here.
        ELISDONTUSEPLEASETRANSLATE_PAUSCHAL_CHANGE_SDG: TODO: type description
            here.
        ELISDONTUSEPLEASETRANSLATE_PAUSCHAL_CHANGE_BORD: TODO: type
            description here.
        LUMPSUMFORTOURCHANGED: TODO: type description here.
        ELISDONTUSEPLEASETRANSLATE_PAUSCHAL_CHANGE_LPOSNR: TODO: type
            description here.
        SUBSEQUENTDELIVERYGENERATED: TODO: type description here.
        SUBSEQUENTDELIVERYCREATED: TODO: type description here.
        UNLOADINGORDERGATEASSIGNED: TODO: type description here.
        INVOICEGENERATEDNEW: TODO: type description here.
        ORDERCANCELLED: TODO: type description here.
        ADDITIONALCHARGINGCANCELLEDNOTNEW: TODO: type description here.
        ORDERFOLLOWUP: TODO: type description here.
        SHIPMENTDIRECTSET: TODO: type description here.
        SHIPMENTDIRECTREMOVE: TODO: type description here.
        TOURDIALOG0: TODO: type description here.
        TOURDIALOG1: TODO: type description here.
        TOURDIALOG2: TODO: type description here.
        TOURDIALOG3: TODO: type description here.
        TOURDIALOG4: TODO: type description here.
        TOURDIALOG5: TODO: type description here.
        TOURDIALOG6: TODO: type description here.
        TOURDIALOG7: TODO: type description here.
        TOURDIALOG8: TODO: type description here.
        TOURDIALOG9: TODO: type description here.
        TOURDIALOG10: TODO: type description here.
        TOURDIALOG11: TODO: type description here.
        TOURDIALOG12: TODO: type description here.
        TOURDIALOG13: TODO: type description here.
        TOURDIALOG14: TODO: type description here.
        TOURDIALOG15: TODO: type description here.
        TOURDIALOG16: TODO: type description here.
        TOURDIALOG17: TODO: type description here.
        TOURDIALOG18: TODO: type description here.
        TOURDIALOG19: TODO: type description here.
        TOURDIALOG20: TODO: type description here.
        TOURDIALOG21: TODO: type description here.
        TOURDIALOG22: TODO: type description here.
        TOURDIALOG23: TODO: type description here.
        TOURDIALOG24: TODO: type description here.
        TOURDIALOG25: TODO: type description here.
        TOURDIALOG26: TODO: type description here.
        TOURDIALOG27: TODO: type description here.
        TOURDIALOG28: TODO: type description here.
        TOURDIALOG29: TODO: type description here.
        TOURDIALOG30: TODO: type description here.
        TOURDIALOG31: TODO: type description here.
        TOURDIALOG32: TODO: type description here.
        TOURDIALOG33: TODO: type description here.
        TOURDIALOG34: TODO: type description here.
        TOURDIALOG35: TODO: type description here.
        TOURDIALOG36: TODO: type description here.
        TOURDIALOG37: TODO: type description here.
        TOURDIALOG38: TODO: type description here.
        TOURDIALOG39: TODO: type description here.
        TOURDIALOG40: TODO: type description here.
        TOURDIALOG41: TODO: type description here.
        TOURDIALOG42: TODO: type description here.
        TOURDIALOG43: TODO: type description here.
        TOURDIALOG44: TODO: type description here.
        TOURDIALOG45: TODO: type description here.
        TOURDIALOG46: TODO: type description here.
        TOURDIALOG47: TODO: type description here.
        TOURDIALOG48: TODO: type description here.
        TOURDIALOG49: TODO: type description here.
        TOURDIALOG50: TODO: type description here.
        TOURDIALOG51: TODO: type description here.
        TOURDIALOG52: TODO: type description here.
        TOURDIALOG53: TODO: type description here.
        TOURDIALOG54: TODO: type description here.
        TOURDIALOG55: TODO: type description here.
        TOURDIALOG56: TODO: type description here.
        TOURDIALOG57: TODO: type description here.
        TOURDIALOG58: TODO: type description here.
        TOURDIALOG59: TODO: type description here.
        TOURDIALOG60: TODO: type description here.
        TOURDIALOG61: TODO: type description here.
        TOURDIALOG62: TODO: type description here.
        TOURDIALOG63: TODO: type description here.
        TOURDIALOG64: TODO: type description here.
        TOURDIALOG65: TODO: type description here.
        TOURDIALOG66: TODO: type description here.
        TOURDIALOG67: TODO: type description here.
        TOURDIALOG68: TODO: type description here.
        TOURDIALOG69: TODO: type description here.
        TOURDIALOG70: TODO: type description here.
        TOURDIALOG71: TODO: type description here.
        TOURDIALOG72: TODO: type description here.
        TOURDIALOG73: TODO: type description here.
        TOURDIALOG74: TODO: type description here.
        TOURDIALOG75: TODO: type description here.
        TOURDIALOG76: TODO: type description here.
        TOURDIALOG77: TODO: type description here.
        TOURDIALOG78: TODO: type description here.
        TOURDIALOG79: TODO: type description here.
        TOURDIALOG80: TODO: type description here.
        TOURDIALOG81: TODO: type description here.
        TOURDIALOG82: TODO: type description here.
        TOURDIALOG83: TODO: type description here.
        TOURDIALOG84: TODO: type description here.
        TOURDIALOG85: TODO: type description here.
        TOURDIALOG86: TODO: type description here.
        TOURDIALOG87: TODO: type description here.
        TOURDIALOG88: TODO: type description here.
        TOURDIALOG89: TODO: type description here.
        TOURDIALOG90: TODO: type description here.
        TOURDIALOG91: TODO: type description here.
        TOURDIALOG92: TODO: type description here.
        TOURDIALOG93: TODO: type description here.
        TOURDIALOG94: TODO: type description here.
        TOURDIALOG95: TODO: type description here.
        TOURDIALOG96: TODO: type description here.
        TOURDIALOG97: TODO: type description here.
        TOURDIALOG98: TODO: type description here.
        TOURDIALOG99: TODO: type description here.
        ORDERDIALOG0: TODO: type description here.
        ORDERDIALOG1: TODO: type description here.
        ORDERDIALOG2: TODO: type description here.
        ORDERDIALOG3: TODO: type description here.
        ORDERDIALOG4: TODO: type description here.
        ORDERDIALOG5: TODO: type description here.
        ORDERDIALOG6: TODO: type description here.
        ORDERDIALOG7: TODO: type description here.
        ORDERDIALOG8: TODO: type description here.
        ORDERDIALOG9: TODO: type description here.
        ORDERDIALOG10: TODO: type description here.
        ORDERDIALOG11: TODO: type description here.
        ORDERDIALOG12: TODO: type description here.
        ORDERDIALOG13: TODO: type description here.
        ORDERDIALOG14: TODO: type description here.
        ORDERDIALOG15: TODO: type description here.
        ORDERDIALOG16: TODO: type description here.
        ORDERDIALOG17: TODO: type description here.
        ORDERDIALOG18: TODO: type description here.
        ORDERDIALOG19: TODO: type description here.
        ORDERDIALOG20: TODO: type description here.
        ORDERDIALOG21: TODO: type description here.
        ORDERDIALOG22: TODO: type description here.
        ORDERDIALOG23: TODO: type description here.
        ORDERDIALOG24: TODO: type description here.
        ORDERDIALOG25: TODO: type description here.
        ORDERDIALOG26: TODO: type description here.
        ORDERDIALOG27: TODO: type description here.
        ORDERDIALOG28: TODO: type description here.
        ORDERDIALOG29: TODO: type description here.
        ORDERDIALOG30: TODO: type description here.
        ORDERDIALOG31: TODO: type description here.
        ORDERDIALOG32: TODO: type description here.
        ORDERDIALOG33: TODO: type description here.
        ORDERDIALOG34: TODO: type description here.
        ORDERDIALOG35: TODO: type description here.
        ORDERDIALOG36: TODO: type description here.
        ORDERDIALOG37: TODO: type description here.
        ORDERDIALOG38: TODO: type description here.
        ORDERDIALOG39: TODO: type description here.
        ORDERDIALOG40: TODO: type description here.
        ORDERDIALOG41: TODO: type description here.
        ORDERDIALOG42: TODO: type description here.
        ORDERDIALOG43: TODO: type description here.
        ORDERDIALOG44: TODO: type description here.
        ORDERDIALOG45: TODO: type description here.
        ORDERDIALOG46: TODO: type description here.
        ORDERDIALOG47: TODO: type description here.
        ORDERDIALOG48: TODO: type description here.
        ORDERDIALOG49: TODO: type description here.
        ORDERDIALOG50: TODO: type description here.
        ORDERDIALOG51: TODO: type description here.
        ORDERDIALOG52: TODO: type description here.
        ORDERDIALOG53: TODO: type description here.
        ORDERDIALOG54: TODO: type description here.
        ORDERDIALOG55: TODO: type description here.
        ORDERDIALOG56: TODO: type description here.
        ORDERDIALOG57: TODO: type description here.
        ORDERDIALOG58: TODO: type description here.
        ORDERDIALOG59: TODO: type description here.
        ORDERDIALOG60: TODO: type description here.
        ORDERDIALOG61: TODO: type description here.
        ORDERDIALOG62: TODO: type description here.
        ORDERDIALOG63: TODO: type description here.
        ORDERDIALOG64: TODO: type description here.
        ORDERDIALOG65: TODO: type description here.
        ORDERDIALOG66: TODO: type description here.
        ORDERDIALOG67: TODO: type description here.
        ORDERDIALOG68: TODO: type description here.
        ORDERDIALOG69: TODO: type description here.
        ORDERDIALOG70: TODO: type description here.
        ORDERDIALOG71: TODO: type description here.
        ORDERDIALOG72: TODO: type description here.
        ORDERDIALOG73: TODO: type description here.
        ORDERDIALOG74: TODO: type description here.
        ORDERDIALOG75: TODO: type description here.
        ORDERDIALOG76: TODO: type description here.
        ORDERDIALOG77: TODO: type description here.
        ORDERDIALOG78: TODO: type description here.
        ORDERDIALOG79: TODO: type description here.
        ORDERDIALOG80: TODO: type description here.
        ORDERDIALOG81: TODO: type description here.
        ORDERDIALOG82: TODO: type description here.
        ORDERDIALOG83: TODO: type description here.
        ORDERDIALOG84: TODO: type description here.
        ORDERDIALOG85: TODO: type description here.
        ORDERDIALOG86: TODO: type description here.
        ORDERDIALOG87: TODO: type description here.
        ORDERDIALOG88: TODO: type description here.
        ORDERDIALOG89: TODO: type description here.
        ORDERDIALOG90: TODO: type description here.
        ORDERDIALOG91: TODO: type description here.
        ORDERDIALOG92: TODO: type description here.
        ORDERDIALOG93: TODO: type description here.
        ORDERDIALOG94: TODO: type description here.
        ORDERDIALOG95: TODO: type description here.
        ORDERDIALOG96: TODO: type description here.
        ORDERDIALOG97: TODO: type description here.
        ORDERDIALOG98: TODO: type description here.
        ORDERDIALOG99: TODO: type description here.
        ELISDONTUSEPLEASETRANSLATE_ROLLKARTEN_RUECKMELDUNG: TODO: type
            description here.
        CASHONDELIVERYALLCOLLECTED: TODO: type description here.
        CASHONDELIVERYPARTLYCOLLECTED: TODO: type description here.
        CASHONDELIVERYNOTCOLLECTED: TODO: type description here.
        INTERNALCOSTALLOCATIONORDERRECEIVED: TODO: type description here.
        INTERNALCOSTALLOCATIONREDEMPTIONOFOUTPUT: TODO: type description
            here.
        INTERNALCOSTALLOCATIONORDERDELIVERED: TODO: type description here.
        INTERNALCOSTALLOCATIONREDEMPTIONOFDELIVERY: TODO: type description
            here.
        TOURDIVIDEBYSPLITTING: TODO: type description here.
        ORDERGOTPOSITIONNUMBER: TODO: type description here.
        OFFERCONDITIONCOPIEDTOORDER: TODO: type description here.
        DOSSIER_PORTMASTERINFOTEXT: TODO: type description here.
        DOSSIER_PORTMASTERERRORMESSAGE: TODO: type description here.
        DOSSIER_PORTMASTERNUMBERGENERATED: TODO: type description here.
        ATLIS_TRANSMITTED: TODO: type description here.
        ATLIS_APPROVED: TODO: type description here.
        ATLIS_CUSTOMS_INCOMINGSTATE: TODO: type description here.
        ATLIS_CUSTOMS_ERRORMSG: TODO: type description here.
        ADDITIONALCOSTORDERNOTHANDEDOVER: TODO: type description here.
        ADDITIONALCOSTORDERALREADYHANDEDOVER: TODO: type description here.
        ADDITIONALCOSTORDERHANDEDOVER: TODO: type description here.
        ADDITIONALCOSTNOCALCULATIONACCORDINGTOCONFIGURATION: TODO: type
            description here.
        ADDITIONALCOSTNOCALCULATIONACCORDINGTOUSER: TODO: type description
            here.
        ADDITIONALCOSTCALCULATIONDONE: TODO: type description here.
        CALCULATIONSIGNEDIN: TODO: type description here.
        ELISDONTUSEPLEASETRANSLATE_SYSTEMVERKEHR_DIENSTLEISTER_SERVICE_MANUELL_
            GESETZT: TODO: type description here.
        ELISDONTUSEPLEASETRANSLATE_SYSTEM_VERKEHR_STANDARD_DIENSTLEISTER_SERVIC
            E_GESETZT: TODO: type description here.
        ELISDONTUSEPLEASETRANSLATE_SYSTEM_VERKEHR_STANDARD_DIENSTLEISTER_SERVIC
            E_GELOESCHT: TODO: type description here.
        ELISDONTUSEPLEASETRANSLATE_SYSTEM_VERKEHR_DIENSTLEISTER_LABEL_GEDRUCKT:
            TODO: type description here.
        ELISDONTUSEPLEASETRANSLATE_SYSTEM_VERKEHR_DIENSTLEISTER_LABEL_GENERIERU
            NGSFEHLER: TODO: type description here.
        LOGPROVIDER_LOGISTICPRODUCT_SUCCEEDED: TODO: type description here.
        LOGPROVIDER_LOGISTICPRODUCT_FAILED: TODO: type description here.
        LOGPROVIDER_LOGISTICTEMPLATE_SUCCEEDED: TODO: type description here.
        LOGPROVIDER_LOGISTICTEMPLATE_NONUNIQUETRANSSHIPMENTPOINT: TODO: type
            description here.
        PLANNINGCOMPLETED: TODO: type description here.
        FOREIGNTOURNRASSIGNMENT: TODO: type description here.
        CONTAINERASSIGNMENTMANUALLYCHANGED: TODO: type description here.
        LOADINGORDERGATEASSIGNED: TODO: type description here.
        LOADINGDEVICEAUTOMATICALLYBOOKED: TODO: type description here.
        LOADINGDEVICEBOOKINGDECLINED: TODO: type description here.
        LOADINGDEVICEMOVEMENTCAPTURED: TODO: type description here.
        LOADINGDEVICEBOOKED: TODO: type description here.
        LOADINGDEVICEMOVEMENTDELETED: TODO: type description here.
        TRANSSHIPMENTBORDEROCREATE: TODO: type description here.
        TRANSSHIPMENTBORDERODESTROY: TODO: type description here.
        RETURNGENERATEDFROM: TODO: type description here.
        SHIPMENTDIVIDED: TODO: type description here.
        SHIPMENTNEW: TODO: type description here.
        SHIPMENTDELETED: TODO: type description here.
        SHIPMENTTOGETHER: TODO: type description here.
        SHIPMENTAPPROVEDNOSECTIONCORRECTION: TODO: type description here.
        INBOUNDORDERLINK: TODO: type description here.
        INBOUNDORDERUNLINK: TODO: type description here.
        SHIPMENTABUNDANTINGOODSRECEIPT: TODO: type description here.
        VDASTALLMONEYSAVED: TODO: type description here.
        VDASAVEBORDEROAUTOFAILED: TODO: type description here.
        VDASAVEBORDEROSUCCESS: TODO: type description here.
        VDATIMEFRAMEIDSAVED: TODO: type description here.
        OAORDERASSIGNED: TODO: type description here.
        OAVDAORDERASSIGNED: TODO: type description here.
        VDABORDEROSEND: TODO: type description here.
        TDSCREATED: TODO: type description here.
        VDAADVICECREATED: TODO: type description here.
        VDAADVICERELEASED: TODO: type description here.
        VDASETTOURAPPROVED: TODO: type description here.
        ASSIGNEDTOHALLROW: TODO: type description here.
        RELEASEDFROMHALLROW: TODO: type description here.
        RETURNSHIPMENTCREATED: TODO: type description here.
        TELEMATICACTUALLORRYGPSFORSHIPMENT: TODO: type description here.
        TELEMATICACTUALTRAILERGPSFORSHIPMENT: TODO: type description here.
        TELEMATICACTUALLORRYGPSFORLASTSHIPMENT: TODO: type description here.
        TELEMATICACTUALTRAILERGPSFORLASTSHIPMENT: TODO: type description
            here.
        COSTALLOCATION_DEBIT_PRINTEDSHARP: TODO: type description here.
        COSTALLOCATION_DEBIT_PRINTEDPROFORMA: TODO: type description here.
        COSTALLOCATION_CREDIT_PRINTEDSHARP: TODO: type description here.
        COSTALLOCATION_CREDIT_PRINTEDPROFORMA: TODO: type description here.
        COSTALLOCATION_CREDIT_INVOICED: TODO: type description here.
        COSTALLOCATIONDEBITCALCULATIONCANCELED: TODO: type description here.
        COSTALLOCATIONDEBITINVOICECANCELED: TODO: type description here.
        COSTALLOCATIONCREDITCALCULATIONCANCELED: TODO: type description here.
        COSTALLOCATIONCREDITINVOICECANCELED: TODO: type description here.
        ETATOOLATE: TODO: type description here.
        ETAINTIME: TODO: type description here.
        ORDERCREATEDBYCOPY: TODO: type description here.

    """

    ENUM_NONE = 'None'

    ORDERFROMEDI = 'OrderFromEDI'

    ORDERFROMEDIWITHERROR = 'OrderFromEDIWithError'

    ORDERCREATED = 'OrderCreated'

    TOURSHIPMENTASSIGNED = 'TourShipmentAssigned'

    TOURSHIPMENTASSIGNEDBYSCANNING = 'TourShipmentAssignedByScanning'

    TOURSHIPMENTRELEASED = 'TourShipmentReleased'

    TOURGENERATED = 'TourGenerated'

    TOURGENERATEDWITHOPENLOADINGORDER = 'TourGeneratedWithOpenLoadingOrder'

    TOURDELETED = 'TourDeleted'

    FUNCTIONSETLOADINGAPPOINTMENT = 'FunctionSetLoadingAppointment'

    TOURTOARCHIV = 'TourToArchiv'

    ORDERCHANGED = 'OrderChanged'

    ORDERCHANGEDWITHERROR = 'OrderChangedWithError'

    ORDERCHANGEDAUTOMATICALLY = 'OrderChangedAutomatically'

    ORDERCHANGEDFROMADVICETONORMAL = 'OrderChangedFromAdviceToNormal'

    SHIPMENTCHANGEDFROMSCHEDULE = 'ShipmentChangedFromSchedule'

    STATETOURPLANED = 'StateTourPlaned'

    STATETOUROPEN = 'StateTourOpen'

    BORDEROCONFIRMED = 'BorderoConfirmed'

    BORDEROREMOVED = 'BorderoRemoved'

    BORDEROCONFIRMEDALL = 'BorderoConfirmedAll'

    AUTOBOOKSUCCEEDED = 'AutoBookSucceeded'

    AUTOBOOKFAILED = 'AutoBookFailed'

    LDTRANSACTIONSAVED = 'LDTransactionSaved'

    LDTRANSACTIONBOOKED = 'LDTransactionBooked'

    LDTRANSACTIONDELETED = 'LDTransactionDeleted'

    TOURFROMARCHIV = 'TourFromArchiv'

    TOURBACKTODELIVERD = 'TourBackToDeliverd'

    TOURBACKTODISPATCHED = 'TourBackToDispatched'

    ELISDONTUSEPLEASETRANSLATE_DFUE_AVIS_FERTIG = 'ELISDontUsePleaseTranslate_DFUE_AVIS_FERTIG'

    ORDERCHANGEDFROMUNCOMPLETETONORMAL = 'OrderChangedFromUncompleteToNormal'

    ORDERCREATEDINSPLITTING = 'OrderCreatedInSplitting'

    ORDERDELETEDBYSPLITTING = 'OrderDeletedBySplitting'

    ORDERSPLITDELETED = 'OrderSplitDeleted'

    SSCCSPLITTING = 'SSCCSplitting'

    LOCKEDINSPLITTING = 'LockedInSplitting'

    ORDERISSPLITTET = 'OrderIsSplittet'

    ASSIGNEDTOBORDERO = 'AssignedToBordero'

    RELEASEDFROMBORDERO = 'ReleasedFromBordero'

    ELISDONTUSEPLEASETRANSLATE_GEAENDERT = 'ELISDontUsePleaseTranslate_GEAENDERT'

    ELISDONTUSEPLEASETRANSLATE_WA_GEBUCHT = 'ELISDontUsePleaseTranslate_WA_GEBUCHT'

    LOADINGLISTPRINTED = 'LoadingListPrinted'

    BORDEROORROLLKARTEPRINTED = 'BorderoOrRollkartePrinted'

    TOINTRANSIT = 'ToInTransit'

    SHIPMENTSINTRANSIT = 'ShipmentsInTransit'

    SHIPMENTSINTRANSITALL = 'ShipmentsInTransitAll'

    ELISDONTUSEPLEASETRANSLATE_ZU_LL = 'ELISDontUsePleaseTranslate_ZU_LL'

    ELISDONTUSEPLEASETRANSLATE_ZU_BORDERO = 'ELISDontUsePleaseTranslate_ZU_BORDERO'

    ELISDONTUSEPLEASETRANSLATE_ENTLADEBERICHT = 'ELISDontUsePleaseTranslate_ENTLADEBERICHT'

    ELISDONTUSEPLEASETRANSLATE_ENTLADEBERICHT_IMPORT = 'ELISDontUsePleaseTranslate_ENTLADEBERICHT_IMPORT'

    ELISDONTUSEPLEASETRANSLATE_ENTLADEBERICHT_IM_POSI = 'ELISDontUsePleaseTranslate_ENTLADEBERICHT_IM_POSI'

    ELISDONTUSEPLEASETRANSLATE_ENTLADEBERICHT_EXPORT = 'ELISDontUsePleaseTranslate_ENTLADEBERICHT_EXPORT'

    DELETED = 'Deleted'

    SPECIALINVOICEDELETED = 'SpecialInvoiceDeleted'

    ELISDONTUSEPLEASETRANSLATE_AUF_EXPORTIERT = 'ELISDontUsePleaseTranslate_AUF_EXPORTIERT'

    ELISDONTUSEPLEASETRANSLATE_TOUR_EXPORTIERT = 'ELISDontUsePleaseTranslate_TOUR_EXPORTIERT'

    ELISDONTUSEPLEASETRANSLATE_RECADV_BESTAETIGT = 'ELISDontUsePleaseTranslate_RECADV_BESTAETIGT'

    ELISDONTUSEPLEASETRANSLATE_RECADV_ZURUECK_OFFEN = 'ELISDontUsePleaseTranslate_RECADV_ZURUECK_OFFEN'

    ELISDONTUSEPLEASETRANSLATE_RECADV_LEERGUT_ANLEGEN = 'ELISDontUsePleaseTranslate_RECADV_LEERGUT_ANLEGEN'

    ELISDONTUSEPLEASETRANSLATE_RECADV_LEERGUT_ANGELEGT = 'ELISDontUsePleaseTranslate_RECADV_LEERGUT_ANGELEGT'

    ELISDONTUSEPLEASETRANSLATE_RECADV_GESENDET = 'ELISDontUsePleaseTranslate_RECADV_GESENDET'

    ELISDONTUSEPLEASETRANSLATE_RE_SCHARF_GEDRUCKT = 'ELISDontUsePleaseTranslate_RE_SCHARF_GEDRUCKT'

    ELISDONTUSEPLEASETRANSLATE_GS_SCHARF_GEDRUCKT = 'ELISDontUsePleaseTranslate_GS_SCHARF_GEDRUCKT'

    ELISDONTUSEPLEASETRANSLATE_RE_PROFORMA_GEDRUCKT = 'ELISDontUsePleaseTranslate_RE_PROFORMA_GEDRUCKT'

    ELISDONTUSEPLEASETRANSLATE_GS_PROFORMA_GEDRUCKT = 'ELISDontUsePleaseTranslate_GS_PROFORMA_GEDRUCKT'

    DEBITCALCULATIONCOMPLETED = 'DebitCalculationCompleted'

    DEBITCALCULATIONSKIPPED = 'DebitCalculationSkipped'

    CREDITCALCULATIONCOMPLETED = 'CreditCalculationCompleted'

    CREDITCALCULATIONSKIPPED = 'CreditCalculationSkipped'

    CHANGEDFREIGHTTERMTOINCOTERM = 'ChangedFreightTermToIncoterm'

    CHANGE_FREIGHTTERM_FOR_CALCSHIPMENT = 'Change_Freightterm_For_CalcShipment'

    ELISDONTUSEPLEASETRANSLATE_RE_EXPORTIERT = 'ELISDontUsePleaseTranslate_RE_EXPORTIERT'

    ELISDONTUSEPLEASETRANSLATE_GS_EXPORTIERT = 'ELISDontUsePleaseTranslate_GS_EXPORTIERT'

    ELISDONTUSEPLEASETRANSLATE_LD_OFFEN = 'ELISDontUsePleaseTranslate_LD_OFFEN'

    ELISDONTUSEPLEASETRANSLATE_LD_DISPONIERT = 'ELISDontUsePleaseTranslate_LD_DISPONIERT'

    ELISDONTUSEPLEASETRANSLATE_LD_UNTERWEGS = 'ELISDontUsePleaseTranslate_LD_UNTERWEGS'

    ELISDONTUSEPLEASETRANSLATE_LD_BESTAETIGT = 'ELISDontUsePleaseTranslate_LD_BESTAETIGT'

    ELISDONTUSEPLEASETRANSLATE_LD_UNTERTEILT = 'ELISDontUsePleaseTranslate_LD_UNTERTEILT'

    ELISDONTUSEPLEASETRANSLATE_LD_TEILGENERIERT = 'ELISDontUsePleaseTranslate_LD_TEILGENERIERT'

    DEBITCALCULATIONCANCELED = 'DebitCalculationCanceled'

    DEBITINVOICECANCELED = 'DebitInvoiceCanceled'

    CREDITCALCULATIONCANCELED = 'CreditCalculationCanceled'

    CREDITINVOICECANCELED = 'CreditInvoiceCanceled'

    SHIPMENTLOCKUNLOCKED = 'ShipmentLockUnlocked'

    TOUR_CABOTAGE_CONFLICT = 'Tour_Cabotage_Conflict'

    TOUR_VEHICLELOCKAPPOINTMENT_CONFLICT = 'Tour_VehicleLockAppointment_Conflict'

    TOUR_GREENLICENCEPLATE_CONFLICT = 'Tour_GreenLicenceplate_Conflict'

    TOUR_CABOTAGE_CLEARANCE = 'Tour_Cabotage_Clearance'

    TOUR_VEHICLELOCKAPPOINTMENT_CLEARANCE = 'Tour_VehicleLockAppointment_Clearance'

    TOUR_GREENLICENCEPLATE_CLEARANCE = 'Tour_GreenLicenceplate_Clearance'

    ELISDONTUSEPLEASETRANSLATE_KABOTAGE_FREIGABE = 'ELISDontUsePleaseTranslate_KABOTAGE_FREIGABE'

    SHIPMENTCOMMITED = 'ShipmentCommited'

    ORDERDELIVERED = 'OrderDelivered'

    ELISDONTUSEPLEASETRANSLATE_SDG_ABLIEFERUNG_OK = 'ELISDontUsePleaseTranslate_SDG_ABLIEFERUNG_OK'

    ELISDONTUSEPLEASETRANSLATE_SDG_ABLIEFERUNG_NICHT = 'ELISDontUsePleaseTranslate_SDG_ABLIEFERUNG_NICHT'

    SHIPMENTINTRANSIT = 'ShipmentInTransit'

    SHIPMENTINTRANSITTODESTINATIONFORWARDER = 'ShipmentInTransitToDestinationForwarder'

    ELISDONTUSEPLEASETRANSLATE_SCC_MITDIFF = 'ELISDontUsePleaseTranslate_SCC_MITDIFF'

    ELISDONTUSEPLEASETRANSLATE_SCC_FEHLEND = 'ELISDontUsePleaseTranslate_SCC_FEHLEND'

    ELISDONTUSEPLEASETRANSLATE_SCC_UMDISPO = 'ELISDontUsePleaseTranslate_SCC_UMDISPO'

    ELISDONTUSEPLEASETRANSLATE_SDG_KOMMISSIONIERT = 'ELISDontUsePleaseTranslate_SDG_KOMMISSIONIERT'

    SHIPMENTINBOUNDCOMPLETELYSCANNED = 'ShipmentInboundCompletelyScanned'

    SHIPMENTINBOUNDPARTIALLYSCANNED = 'ShipmentInboundPartiallyScanned'

    SHIPMENTINBOUNDNOTSCANNED = 'ShipmentInboundNotScanned'

    ELISDONTUSEPLEASETRANSLATE_SDG_AUTOENTFIX = 'ELISDontUsePleaseTranslate_SDG_AUTOENTFIX'

    SHIPMENTOUTBOUNDCOMPLETELYSCANNED = 'ShipmentOutboundCompletelyScanned'

    SHIPMENTOUTBOUNDPARTIALLYSCANNED = 'ShipmentOutboundPartiallyScanned'

    SHIPMENTOUTBOUNDNOTSCANNED = 'ShipmentOutboundNotScanned'

    SHIPMENTLOADINGOK = 'ShipmentLoadingOk'

    SHIPMENTINBOUNDPARTIALLYDAMAGED = 'ShipmentInboundPartiallyDamaged'

    SHIPMENTINBOUNDNOTDAMAGED = 'ShipmentInboundNotDamaged'

    SHIPMENTINBOUNDCOMPLETELYDAMAGED = 'ShipmentInboundCompletelyDamaged'

    SHIPMENTOUTBOUNDPARTIALLYDAMAGED = 'ShipmentOutboundPartiallyDamaged'

    SHIPMENTOUTBOUNDNOTDAMAGED = 'ShipmentOutboundNotDamaged'

    SHIPMENTOUTBOUNDCOMPLETELYDAMAGED = 'ShipmentOutboundCompletelyDamaged'

    SHIPMENTINBOUNDPARTIALLYANDDAMAGED = 'ShipmentInboundPartiallyAndDamaged'

    SHIPMENTOUTBOUNDPARTIALLYANDDAMAGED = 'ShipmentOutboundPartiallyAndDamaged'

    ARCHIVEDDOCUMENTMANUALLY = 'ArchivedDocumentManually'

    ARCHIVEDDOCUMENTAUTOMATICALLY = 'ArchivedDocumentAutomatically'

    ARCHIVEDDOCUMENTAUTOMATICALLYIMPORT = 'ArchivedDocumentAutomaticallyImport'

    ELISDONTUSEPLEASETRANSLATE_VDISPO_SPERREN = 'ELISDontUsePleaseTranslate_VDISPO_SPERREN'

    ELISDONTUSEPLEASETRANSLATE_VDISPO_FREIGEBEN = 'ELISDontUsePleaseTranslate_VDISPO_FREIGEBEN'

    ELISDONTUSEPLEASETRANSLATE_VDISPO_ADD = 'ELISDontUsePleaseTranslate_VDISPO_ADD'

    ELISDONTUSEPLEASETRANSLATE_VDISPO_REMOVE = 'ELISDontUsePleaseTranslate_VDISPO_REMOVE'

    ELISDONTUSEPLEASETRANSLATE_PAUSCHAL_CHANGE_SDG = 'ELISDontUsePleaseTranslate_PAUSCHAL_CHANGE_SDG'

    ELISDONTUSEPLEASETRANSLATE_PAUSCHAL_CHANGE_BORD = 'ELISDontUsePleaseTranslate_PAUSCHAL_CHANGE_BORD'

    LUMPSUMFORTOURCHANGED = 'LumpSumForTourChanged'

    ELISDONTUSEPLEASETRANSLATE_PAUSCHAL_CHANGE_LPOSNR = 'ELISDontUsePleaseTranslate_PAUSCHAL_CHANGE_LPOSNR'

    SUBSEQUENTDELIVERYGENERATED = 'SubsequentDeliveryGenerated'

    SUBSEQUENTDELIVERYCREATED = 'SubsequentDeliveryCreated'

    UNLOADINGORDERGATEASSIGNED = 'UnloadingOrderGateAssigned'

    INVOICEGENERATEDNEW = 'InvoiceGeneratedNew'

    ORDERCANCELLED = 'OrderCancelled'

    ADDITIONALCHARGINGCANCELLEDNOTNEW = 'AdditionalChargingCancelledNotNew'

    ORDERFOLLOWUP = 'OrderFollowUp'

    SHIPMENTDIRECTSET = 'ShipmentDirectSet'

    SHIPMENTDIRECTREMOVE = 'ShipmentDirectRemove'

    TOURDIALOG0 = 'TourDialog0'

    TOURDIALOG1 = 'TourDialog1'

    TOURDIALOG2 = 'TourDialog2'

    TOURDIALOG3 = 'TourDialog3'

    TOURDIALOG4 = 'TourDialog4'

    TOURDIALOG5 = 'TourDialog5'

    TOURDIALOG6 = 'TourDialog6'

    TOURDIALOG7 = 'TourDialog7'

    TOURDIALOG8 = 'TourDialog8'

    TOURDIALOG9 = 'TourDialog9'

    TOURDIALOG10 = 'TourDialog10'

    TOURDIALOG11 = 'TourDialog11'

    TOURDIALOG12 = 'TourDialog12'

    TOURDIALOG13 = 'TourDialog13'

    TOURDIALOG14 = 'TourDialog14'

    TOURDIALOG15 = 'TourDialog15'

    TOURDIALOG16 = 'TourDialog16'

    TOURDIALOG17 = 'TourDialog17'

    TOURDIALOG18 = 'TourDialog18'

    TOURDIALOG19 = 'TourDialog19'

    TOURDIALOG20 = 'TourDialog20'

    TOURDIALOG21 = 'TourDialog21'

    TOURDIALOG22 = 'TourDialog22'

    TOURDIALOG23 = 'TourDialog23'

    TOURDIALOG24 = 'TourDialog24'

    TOURDIALOG25 = 'TourDialog25'

    TOURDIALOG26 = 'TourDialog26'

    TOURDIALOG27 = 'TourDialog27'

    TOURDIALOG28 = 'TourDialog28'

    TOURDIALOG29 = 'TourDialog29'

    TOURDIALOG30 = 'TourDialog30'

    TOURDIALOG31 = 'TourDialog31'

    TOURDIALOG32 = 'TourDialog32'

    TOURDIALOG33 = 'TourDialog33'

    TOURDIALOG34 = 'TourDialog34'

    TOURDIALOG35 = 'TourDialog35'

    TOURDIALOG36 = 'TourDialog36'

    TOURDIALOG37 = 'TourDialog37'

    TOURDIALOG38 = 'TourDialog38'

    TOURDIALOG39 = 'TourDialog39'

    TOURDIALOG40 = 'TourDialog40'

    TOURDIALOG41 = 'TourDialog41'

    TOURDIALOG42 = 'TourDialog42'

    TOURDIALOG43 = 'TourDialog43'

    TOURDIALOG44 = 'TourDialog44'

    TOURDIALOG45 = 'TourDialog45'

    TOURDIALOG46 = 'TourDialog46'

    TOURDIALOG47 = 'TourDialog47'

    TOURDIALOG48 = 'TourDialog48'

    TOURDIALOG49 = 'TourDialog49'

    TOURDIALOG50 = 'TourDialog50'

    TOURDIALOG51 = 'TourDialog51'

    TOURDIALOG52 = 'TourDialog52'

    TOURDIALOG53 = 'TourDialog53'

    TOURDIALOG54 = 'TourDialog54'

    TOURDIALOG55 = 'TourDialog55'

    TOURDIALOG56 = 'TourDialog56'

    TOURDIALOG57 = 'TourDialog57'

    TOURDIALOG58 = 'TourDialog58'

    TOURDIALOG59 = 'TourDialog59'

    TOURDIALOG60 = 'TourDialog60'

    TOURDIALOG61 = 'TourDialog61'

    TOURDIALOG62 = 'TourDialog62'

    TOURDIALOG63 = 'TourDialog63'

    TOURDIALOG64 = 'TourDialog64'

    TOURDIALOG65 = 'TourDialog65'

    TOURDIALOG66 = 'TourDialog66'

    TOURDIALOG67 = 'TourDialog67'

    TOURDIALOG68 = 'TourDialog68'

    TOURDIALOG69 = 'TourDialog69'

    TOURDIALOG70 = 'TourDialog70'

    TOURDIALOG71 = 'TourDialog71'

    TOURDIALOG72 = 'TourDialog72'

    TOURDIALOG73 = 'TourDialog73'

    TOURDIALOG74 = 'TourDialog74'

    TOURDIALOG75 = 'TourDialog75'

    TOURDIALOG76 = 'TourDialog76'

    TOURDIALOG77 = 'TourDialog77'

    TOURDIALOG78 = 'TourDialog78'

    TOURDIALOG79 = 'TourDialog79'

    TOURDIALOG80 = 'TourDialog80'

    TOURDIALOG81 = 'TourDialog81'

    TOURDIALOG82 = 'TourDialog82'

    TOURDIALOG83 = 'TourDialog83'

    TOURDIALOG84 = 'TourDialog84'

    TOURDIALOG85 = 'TourDialog85'

    TOURDIALOG86 = 'TourDialog86'

    TOURDIALOG87 = 'TourDialog87'

    TOURDIALOG88 = 'TourDialog88'

    TOURDIALOG89 = 'TourDialog89'

    TOURDIALOG90 = 'TourDialog90'

    TOURDIALOG91 = 'TourDialog91'

    TOURDIALOG92 = 'TourDialog92'

    TOURDIALOG93 = 'TourDialog93'

    TOURDIALOG94 = 'TourDialog94'

    TOURDIALOG95 = 'TourDialog95'

    TOURDIALOG96 = 'TourDialog96'

    TOURDIALOG97 = 'TourDialog97'

    TOURDIALOG98 = 'TourDialog98'

    TOURDIALOG99 = 'TourDialog99'

    ORDERDIALOG0 = 'OrderDialog0'

    ORDERDIALOG1 = 'OrderDialog1'

    ORDERDIALOG2 = 'OrderDialog2'

    ORDERDIALOG3 = 'OrderDialog3'

    ORDERDIALOG4 = 'OrderDialog4'

    ORDERDIALOG5 = 'OrderDialog5'

    ORDERDIALOG6 = 'OrderDialog6'

    ORDERDIALOG7 = 'OrderDialog7'

    ORDERDIALOG8 = 'OrderDialog8'

    ORDERDIALOG9 = 'OrderDialog9'

    ORDERDIALOG10 = 'OrderDialog10'

    ORDERDIALOG11 = 'OrderDialog11'

    ORDERDIALOG12 = 'OrderDialog12'

    ORDERDIALOG13 = 'OrderDialog13'

    ORDERDIALOG14 = 'OrderDialog14'

    ORDERDIALOG15 = 'OrderDialog15'

    ORDERDIALOG16 = 'OrderDialog16'

    ORDERDIALOG17 = 'OrderDialog17'

    ORDERDIALOG18 = 'OrderDialog18'

    ORDERDIALOG19 = 'OrderDialog19'

    ORDERDIALOG20 = 'OrderDialog20'

    ORDERDIALOG21 = 'OrderDialog21'

    ORDERDIALOG22 = 'OrderDialog22'

    ORDERDIALOG23 = 'OrderDialog23'

    ORDERDIALOG24 = 'OrderDialog24'

    ORDERDIALOG25 = 'OrderDialog25'

    ORDERDIALOG26 = 'OrderDialog26'

    ORDERDIALOG27 = 'OrderDialog27'

    ORDERDIALOG28 = 'OrderDialog28'

    ORDERDIALOG29 = 'OrderDialog29'

    ORDERDIALOG30 = 'OrderDialog30'

    ORDERDIALOG31 = 'OrderDialog31'

    ORDERDIALOG32 = 'OrderDialog32'

    ORDERDIALOG33 = 'OrderDialog33'

    ORDERDIALOG34 = 'OrderDialog34'

    ORDERDIALOG35 = 'OrderDialog35'

    ORDERDIALOG36 = 'OrderDialog36'

    ORDERDIALOG37 = 'OrderDialog37'

    ORDERDIALOG38 = 'OrderDialog38'

    ORDERDIALOG39 = 'OrderDialog39'

    ORDERDIALOG40 = 'OrderDialog40'

    ORDERDIALOG41 = 'OrderDialog41'

    ORDERDIALOG42 = 'OrderDialog42'

    ORDERDIALOG43 = 'OrderDialog43'

    ORDERDIALOG44 = 'OrderDialog44'

    ORDERDIALOG45 = 'OrderDialog45'

    ORDERDIALOG46 = 'OrderDialog46'

    ORDERDIALOG47 = 'OrderDialog47'

    ORDERDIALOG48 = 'OrderDialog48'

    ORDERDIALOG49 = 'OrderDialog49'

    ORDERDIALOG50 = 'OrderDialog50'

    ORDERDIALOG51 = 'OrderDialog51'

    ORDERDIALOG52 = 'OrderDialog52'

    ORDERDIALOG53 = 'OrderDialog53'

    ORDERDIALOG54 = 'OrderDialog54'

    ORDERDIALOG55 = 'OrderDialog55'

    ORDERDIALOG56 = 'OrderDialog56'

    ORDERDIALOG57 = 'OrderDialog57'

    ORDERDIALOG58 = 'OrderDialog58'

    ORDERDIALOG59 = 'OrderDialog59'

    ORDERDIALOG60 = 'OrderDialog60'

    ORDERDIALOG61 = 'OrderDialog61'

    ORDERDIALOG62 = 'OrderDialog62'

    ORDERDIALOG63 = 'OrderDialog63'

    ORDERDIALOG64 = 'OrderDialog64'

    ORDERDIALOG65 = 'OrderDialog65'

    ORDERDIALOG66 = 'OrderDialog66'

    ORDERDIALOG67 = 'OrderDialog67'

    ORDERDIALOG68 = 'OrderDialog68'

    ORDERDIALOG69 = 'OrderDialog69'

    ORDERDIALOG70 = 'OrderDialog70'

    ORDERDIALOG71 = 'OrderDialog71'

    ORDERDIALOG72 = 'OrderDialog72'

    ORDERDIALOG73 = 'OrderDialog73'

    ORDERDIALOG74 = 'OrderDialog74'

    ORDERDIALOG75 = 'OrderDialog75'

    ORDERDIALOG76 = 'OrderDialog76'

    ORDERDIALOG77 = 'OrderDialog77'

    ORDERDIALOG78 = 'OrderDialog78'

    ORDERDIALOG79 = 'OrderDialog79'

    ORDERDIALOG80 = 'OrderDialog80'

    ORDERDIALOG81 = 'OrderDialog81'

    ORDERDIALOG82 = 'OrderDialog82'

    ORDERDIALOG83 = 'OrderDialog83'

    ORDERDIALOG84 = 'OrderDialog84'

    ORDERDIALOG85 = 'OrderDialog85'

    ORDERDIALOG86 = 'OrderDialog86'

    ORDERDIALOG87 = 'OrderDialog87'

    ORDERDIALOG88 = 'OrderDialog88'

    ORDERDIALOG89 = 'OrderDialog89'

    ORDERDIALOG90 = 'OrderDialog90'

    ORDERDIALOG91 = 'OrderDialog91'

    ORDERDIALOG92 = 'OrderDialog92'

    ORDERDIALOG93 = 'OrderDialog93'

    ORDERDIALOG94 = 'OrderDialog94'

    ORDERDIALOG95 = 'OrderDialog95'

    ORDERDIALOG96 = 'OrderDialog96'

    ORDERDIALOG97 = 'OrderDialog97'

    ORDERDIALOG98 = 'OrderDialog98'

    ORDERDIALOG99 = 'OrderDialog99'

    ELISDONTUSEPLEASETRANSLATE_ROLLKARTEN_RUECKMELDUNG = 'ELISDontUsePleaseTranslate_ROLLKARTEN_RUECKMELDUNG'

    CASHONDELIVERYALLCOLLECTED = 'CashOnDeliveryAllCollected'

    CASHONDELIVERYPARTLYCOLLECTED = 'CashOnDeliveryPartlyCollected'

    CASHONDELIVERYNOTCOLLECTED = 'CashOnDeliveryNotCollected'

    INTERNALCOSTALLOCATIONORDERRECEIVED = 'InternalCostAllocationOrderReceived'

    INTERNALCOSTALLOCATIONREDEMPTIONOFOUTPUT = 'InternalCostAllocationRedemptionOfOutput'

    INTERNALCOSTALLOCATIONORDERDELIVERED = 'InternalCostAllocationOrderDelivered'

    INTERNALCOSTALLOCATIONREDEMPTIONOFDELIVERY = 'InternalCostAllocationRedemptionOfDelivery'

    TOURDIVIDEBYSPLITTING = 'TourDivideBySplitting'

    ORDERGOTPOSITIONNUMBER = 'OrderGotPositionNumber'

    OFFERCONDITIONCOPIEDTOORDER = 'OfferConditionCopiedToOrder'

    DOSSIER_PORTMASTERINFOTEXT = 'Dossier_PortMasterInfoText'

    DOSSIER_PORTMASTERERRORMESSAGE = 'Dossier_PortMasterErrorMessage'

    DOSSIER_PORTMASTERNUMBERGENERATED = 'Dossier_PortMasterNumberGenerated'

    ATLIS_TRANSMITTED = 'ATLIS_Transmitted'

    ATLIS_APPROVED = 'ATLIS_Approved'

    ATLIS_CUSTOMS_INCOMINGSTATE = 'ATLIS_Customs_IncomingState'

    ATLIS_CUSTOMS_ERRORMSG = 'ATLIS_Customs_ErrorMsg'

    ADDITIONALCOSTORDERNOTHANDEDOVER = 'AdditionalCostOrderNotHandedOver'

    ADDITIONALCOSTORDERALREADYHANDEDOVER = 'AdditionalCostOrderAlreadyHandedOver'

    ADDITIONALCOSTORDERHANDEDOVER = 'AdditionalCostOrderHandedOver'

    ADDITIONALCOSTNOCALCULATIONACCORDINGTOCONFIGURATION = 'AdditionalCostNoCalculationAccordingToConfiguration'

    ADDITIONALCOSTNOCALCULATIONACCORDINGTOUSER = 'AdditionalCostNoCalculationAccordingToUser'

    ADDITIONALCOSTCALCULATIONDONE = 'AdditionalCostCalculationDone'

    CALCULATIONSIGNEDIN = 'CalculationSignedIn'

    ELISDONTUSEPLEASETRANSLATE_SYSTEMVERKEHR_DIENSTLEISTER_SERVICE_MANUELL_GESETZT = 'ELISDontUsePleaseTranslate_SYSTEMVERKEHR_DIENSTLEISTER_SERVICE_MANUELL_GESETZT'

    ELISDONTUSEPLEASETRANSLATE_SYSTEM_VERKEHR_STANDARD_DIENSTLEISTER_SERVICE_GESETZT = 'ELISDontUsePleaseTranslate_SYSTEM_VERKEHR_STANDARD_DIENSTLEISTER_SERVICE_GESETZT'

    ELISDONTUSEPLEASETRANSLATE_SYSTEM_VERKEHR_STANDARD_DIENSTLEISTER_SERVICE_GELOESCHT = 'ELISDontUsePleaseTranslate_SYSTEM_VERKEHR_STANDARD_DIENSTLEISTER_SERVICE_GELOESCHT'

    ELISDONTUSEPLEASETRANSLATE_SYSTEM_VERKEHR_DIENSTLEISTER_LABEL_GEDRUCKT = 'ELISDontUsePleaseTranslate_SYSTEM_VERKEHR_DIENSTLEISTER_LABEL_GEDRUCKT'

    ELISDONTUSEPLEASETRANSLATE_SYSTEM_VERKEHR_DIENSTLEISTER_LABEL_GENERIERUNGSFEHLER = 'ELISDontUsePleaseTranslate_SYSTEM_VERKEHR_DIENSTLEISTER_LABEL_GENERIERUNGSFEHLER'

    LOGPROVIDER_LOGISTICPRODUCT_SUCCEEDED = 'LogProvider_LogisticProduct_Succeeded'

    LOGPROVIDER_LOGISTICPRODUCT_FAILED = 'LogProvider_LogisticProduct_Failed'

    LOGPROVIDER_LOGISTICTEMPLATE_SUCCEEDED = 'LogProvider_LogisticTemplate_Succeeded'

    LOGPROVIDER_LOGISTICTEMPLATE_NONUNIQUETRANSSHIPMENTPOINT = 'LogProvider_LogisticTemplate_NonUniqueTransshipmentPoint'

    PLANNINGCOMPLETED = 'PlanningCompleted'

    FOREIGNTOURNRASSIGNMENT = 'ForeignTourNrAssignment'

    CONTAINERASSIGNMENTMANUALLYCHANGED = 'ContainerAssignmentManuallyChanged'

    LOADINGORDERGATEASSIGNED = 'LoadingOrderGateAssigned'

    LOADINGDEVICEAUTOMATICALLYBOOKED = 'LoadingDeviceAutomaticallyBooked'

    LOADINGDEVICEBOOKINGDECLINED = 'LoadingDeviceBookingDeclined'

    LOADINGDEVICEMOVEMENTCAPTURED = 'LoadingDeviceMovementCaptured'

    LOADINGDEVICEBOOKED = 'LoadingDeviceBooked'

    LOADINGDEVICEMOVEMENTDELETED = 'LoadingDeviceMovementDeleted'

    TRANSSHIPMENTBORDEROCREATE = 'TransshipmentBorderoCreate'

    TRANSSHIPMENTBORDERODESTROY = 'TransshipmentBorderoDestroy'

    RETURNGENERATEDFROM = 'ReturnGeneratedFrom'

    SHIPMENTDIVIDED = 'ShipmentDivided'

    SHIPMENTNEW = 'ShipmentNew'

    SHIPMENTDELETED = 'ShipmentDeleted'

    SHIPMENTTOGETHER = 'ShipmentTogether'

    SHIPMENTAPPROVEDNOSECTIONCORRECTION = 'ShipmentApprovedNoSectionCorrection'

    INBOUNDORDERLINK = 'InboundOrderLink'

    INBOUNDORDERUNLINK = 'InboundOrderUnlink'

    SHIPMENTABUNDANTINGOODSRECEIPT = 'ShipmentAbundantInGoodsReceipt'

    VDASTALLMONEYSAVED = 'VDAStallMoneySaved'

    VDASAVEBORDEROAUTOFAILED = 'VDASaveBorderoAutoFailed'

    VDASAVEBORDEROSUCCESS = 'VDASaveBorderoSuccess'

    VDATIMEFRAMEIDSAVED = 'VDATimeFrameIDSaved'

    OAORDERASSIGNED = 'OAOrderAssigned'

    OAVDAORDERASSIGNED = 'OAVDAOrderAssigned'

    VDABORDEROSEND = 'VDABorderoSend'

    TDSCREATED = 'TDSCreated'

    VDAADVICECREATED = 'VDAAdviceCreated'

    VDAADVICERELEASED = 'VDAAdviceReleased'

    VDASETTOURAPPROVED = 'VDASetTourApproved'

    ASSIGNEDTOHALLROW = 'AssignedToHallRow'

    RELEASEDFROMHALLROW = 'ReleasedFromHallRow'

    RETURNSHIPMENTCREATED = 'ReturnShipmentCreated'

    TELEMATICACTUALLORRYGPSFORSHIPMENT = 'TelematicActualLorryGPSForShipment'

    TELEMATICACTUALTRAILERGPSFORSHIPMENT = 'TelematicActualTrailerGPSForShipment'

    TELEMATICACTUALLORRYGPSFORLASTSHIPMENT = 'TelematicActualLorryGPSForLastShipment'

    TELEMATICACTUALTRAILERGPSFORLASTSHIPMENT = 'TelematicActualTrailerGPSForLastShipment'

    COSTALLOCATION_DEBIT_PRINTEDSHARP = 'CostAllocation_Debit_PrintedSharp'

    COSTALLOCATION_DEBIT_PRINTEDPROFORMA = 'CostAllocation_Debit_PrintedProforma'

    COSTALLOCATION_CREDIT_PRINTEDSHARP = 'CostAllocation_Credit_PrintedSharp'

    COSTALLOCATION_CREDIT_PRINTEDPROFORMA = 'CostAllocation_Credit_PrintedProforma'

    COSTALLOCATION_CREDIT_INVOICED = 'CostAllocation_Credit_Invoiced'

    COSTALLOCATIONDEBITCALCULATIONCANCELED = 'CostAllocationDebitCalculationCanceled'

    COSTALLOCATIONDEBITINVOICECANCELED = 'CostAllocationDebitInvoiceCanceled'

    COSTALLOCATIONCREDITCALCULATIONCANCELED = 'CostAllocationCreditCalculationCanceled'

    COSTALLOCATIONCREDITINVOICECANCELED = 'CostAllocationCreditInvoiceCanceled'

    ETATOOLATE = 'ETATooLate'

    ETAINTIME = 'ETAInTime'

    ORDERCREATEDBYCOPY = 'OrderCreatedByCopy'
