# -*- coding: utf-8 -*-

"""
lispublicservices

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class State3Enum(object):

    """Implementation of the 'State3' enum.

    TODO: type enum description here.

    Attributes:
        NOTSET: TODO: type description here.
        SCANNED: TODO: type description here.
        ARCHIVED: TODO: type description here.
        POSTBOX: TODO: type description here.

    """

    NOTSET = 'NotSet'

    SCANNED = 'Scanned'

    ARCHIVED = 'Archived'

    POSTBOX = 'PostBox'
