# -*- coding: utf-8 -*-

"""
lispublicservices

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class State2Enum(object):

    """Implementation of the 'State2' enum.

    The state of the tour
    DB:Status

    Attributes:
        NOTSET: TODO: type description here.
        OPEN: TODO: type description here.
        PLANNED: TODO: type description here.
        INTRANSIT: TODO: type description here.
        DELIVERED: TODO: type description here.
        APPROVED: TODO: type description here.
        ASSESSED: TODO: type description here.
        PARTIALLYPRINTED: TODO: type description here.
        PRINTED: TODO: type description here.
        ARCHIVED: TODO: type description here.

    """

    NOTSET = 'NotSet'

    OPEN = 'Open'

    PLANNED = 'Planned'

    INTRANSIT = 'InTransit'

    DELIVERED = 'Delivered'

    APPROVED = 'Approved'

    ASSESSED = 'Assessed'

    PARTIALLYPRINTED = 'PartiallyPrinted'

    PRINTED = 'Printed'

    ARCHIVED = 'Archived'
