# -*- coding: utf-8 -*-

"""
lispublicservices

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class TextTypeEnum(object):

    """Implementation of the 'TextType' enum.

    Gets or sets TextType.

    Attributes:
        TEXT: TODO: type description here.
        INFORMATION: TODO: type description here.
        INVOICE: TODO: type description here.
        CREDITNOTE: TODO: type description here.
        DELIVERY: TODO: type description here.
        SHIPPINGORDER: TODO: type description here.
        AGREEMENT: TODO: type description here.
        DISPOSITION: TODO: type description here.
        LABEL: TODO: type description here.
        ADVANCED1: TODO: type description here.
        ADVANCED2: TODO: type description here.
        CANCELATION: TODO: type description here.

    """

    TEXT = 'Text'

    INFORMATION = 'Information'

    INVOICE = 'Invoice'

    CREDITNOTE = 'CreditNote'

    DELIVERY = 'Delivery'

    SHIPPINGORDER = 'ShippingOrder'

    AGREEMENT = 'Agreement'

    DISPOSITION = 'Disposition'

    LABEL = 'Label'

    ADVANCED1 = 'Advanced1'

    ADVANCED2 = 'Advanced2'

    CANCELATION = 'Cancelation'
