# -*- coding: utf-8 -*-

"""
lispublicservices

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class TimeTableItemTypeEnum(object):

    """Implementation of the 'TimeTableItemType' enum.

    Gets or sets the TimeTableItemType property. This property depends on the
    database field TimeTableItemType.

    Attributes:
        NONE: TODO: type description here.
        TRAIN: TODO: type description here.

    """

    ENUM_NONE = 'None'

    TRAIN = 'Train'
