# -*- coding: utf-8 -*-

"""
lispublicservices

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class TransshipmentBorderoHandoverEnum(object):

    """Implementation of the 'TransshipmentBorderoHandover' enum.

    Gets or sets the transshipment bordero handover.

    Attributes:
        NONE: TODO: type description here.
        DIRECT: TODO: type description here.

    """

    ENUM_NONE = 'None'

    DIRECT = 'Direct'
