# -*- coding: utf-8 -*-

"""
lispublicservices

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class TunnelCategoryEnum(object):

    """Implementation of the 'TunnelCategory' enum.

    Gets or sets the tunnel category.

    Attributes:
        A: TODO: type description here.
        B: TODO: type description here.
        C: TODO: type description here.
        D: TODO: type description here.
        E: TODO: type description here.

    """

    A = 'A'

    B = 'B'

    C = 'C'

    D = 'D'

    E = 'E'
