# -*- coding: utf-8 -*-

"""
lispublicservices

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class Type1Enum(object):

    """Implementation of the 'Type1' enum.

    Gets or sets Type.

    Attributes:
        COMMON: TODO: type description here.
        MASTER: TODO: type description here.

    """

    COMMON = 'Common'

    MASTER = 'Master'
