# -*- coding: utf-8 -*-

"""
lispublicservices

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class TypeEnum(object):

    """Implementation of the 'Type' enum.

    Gets or sets the type.

    Attributes:
        NOTSET: TODO: type description here.
        INVOICING: TODO: type description here.
        CALCULATION: TODO: type description here.

    """

    NOTSET = 'NotSet'

    INVOICING = 'Invoicing'

    CALCULATION = 'Calculation'
