# -*- coding: utf-8 -*-

"""
lispublicservices

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class UsedRoutingProviderEnum(object):

    """Implementation of the 'UsedRoutingProvider' enum.

    Gets or sets the used routing provider.

    Attributes:
        NOTSET: TODO: type description here.
        NOPROVIDER: TODO: type description here.
        LIS: TODO: type description here.
        PTVMAPSERVER: TODO: type description here.
        PTVCONTROLS: TODO: type description here.
        CAROLA: TODO: type description here.
        NOKIA: TODO: type description here.
        DISTANCEROADWORK: TODO: type description here.
        DISTANCEROADWORKOLD: TODO: type description here.
        PTVXSERVER: TODO: type description here.
        NODE: TODO: type description here.
        GEOCOORDINATE: TODO: type description here.
        MAPPOINT: TODO: type description here.
        MAPPOINTZIPCODE: TODO: type description here.
        AIRLINE: TODO: type description here.
        SEQUENCE: TODO: type description here.
        STRAIGHTDISTANCE: TODO: type description here.
        CANCEL: TODO: type description here.
        OSRM: TODO: type description here.
        ASTAG: TODO: type description here.
        ASTAGOLD: TODO: type description here.
        H0: TODO: type description here.
        ONLYFORTESTING: TODO: type description here.
        EMPTY: TODO: type description here.

    """

    NOTSET = 'NotSet'

    NOPROVIDER = 'NoProvider'

    LIS = 'LIS'

    PTVMAPSERVER = 'PTVMapServer'

    PTVCONTROLS = 'PTVControls'

    CAROLA = 'Carola'

    NOKIA = 'Nokia'

    DISTANCEROADWORK = 'DistanceRoadWork'

    DISTANCEROADWORKOLD = 'DistanceRoadWorkOld'

    PTVXSERVER = 'PTVxServer'

    NODE = 'Node'

    GEOCOORDINATE = 'GeoCoordinate'

    MAPPOINT = 'MapPoint'

    MAPPOINTZIPCODE = 'MapPointZipCode'

    AIRLINE = 'AirLine'

    SEQUENCE = 'Sequence'

    STRAIGHTDISTANCE = 'StraightDistance'

    CANCEL = 'Cancel'

    OSRM = 'OSRM'

    ASTAG = 'Astag'

    ASTAGOLD = 'AstagOld'

    H0 = 'H0'

    ONLYFORTESTING = 'OnlyForTesting'

    EMPTY = 'Empty'
